### ISSUE TITLE
label on DM  images etc which have been renamed in Windows

### ISSUE THREAD

**Issue by mwalls** [hyperspy/hyperspy#1068] opened 2016-06-14 12:25 UTC
This is a bug arising possibly in Windows or DM, but it can cause confusion when using Hyperspy. A file called "oldname.dm4" which is renamed (in Windows) "newname.dm4" can be loaded using 
s= hs.load("newname.dm4")
but when plotted gives "oldname" as the label in the plot window. Where does hyperspy read the name of the file? Is it possibly in some obscure tag which DM no longer uses? I cannot find any trace of the old name in the DM file, but I guess it must be there somewhere.

Anyway it's not a big problem once you know what's happening, but it can be confusing.

**Comment by francisco-dlp** [comment] 2016-06-14 14:36
I am not sure if this is a bug. HyperSpy simply prints the title that it finds in the file's metadata. By default DM takes the title from the file name, and obviously renaming it doesn't update the title. I see how this can be confusing, but I don't know how we could do it better.

**Comment by mwalls** [comment] 2016-06-14 16:24
Cannot Hyperspy use the filename, instead of the title in the metadata, for the plot window title? This is what DM itself seems to do; when you open a renamed file in DM the title of the window is the new name. 
Incidentally, this particular metadata seems quite well hidden in the DM files we have.  How does Hyperspy find it? It's not in the metadata listed in the tags and it cannot be found by opening the file as text. Is it stored in some non ascii format? 

Anyway, not a priority, I admit...

**Comment by francisco-dlp** [comment] 2016-06-14 17:00
Yes, it's stored in bin format.

The issue is that HyperSpy doesn't display the file name in the plot window title but the title as defined in `metadata.General.title`. As the DM files include a title in the metadata it seems reasonable to set hspy's `metadata.General.title` to that title. If that title was always the original file name, then we could take the file name instead. However, are you sure that this is the case i.e. isn't there a way to change the title of a DM signal?

**Comment by mwalls** [comment] 2016-06-15 09:58
I'm not sure I understand your question. There is of course a way to change the title of a DM file, by just saving it (in DM or in windows) with a new name.  I'm not sure I know what you mean by changing the title of a **signal**. When you create an image you can give it a title as the first parameter, eg : image im = BinaryImage( "myimage", 256, 256).The only way I can find to ask what the title of an existing image is, is with the command
String title =  WindowGetTitle( i ) where i is the window number. This 'window' title and the previously defined image title seem always to be the same. If you cange this title or If you change the filename in windows and open it again the window title has become the new name. Wherever the metadata with the old title is, it seems to be inaccessible. I can't find find it and neither can Marcel. Hyperspy is very claver! But it would seem to be some old metadata that is no longer used by DM that you have managed to unearth! I would suggest using the filename instead. A user here (Marta) became confused , not knowing what data she was looking at. A user with no contact with anyone to do with Hyperspy might thing its bugging and give up. What do you think. Have I not understood?

**Comment by mwalls** [comment] 2016-06-15 12:00
I should correct the last entry a bit. You have to use String title = WindowGetTitle( win) where "win" is a "documentwindow" indexed "i". We are still looking to find out whether the old name is somehow accessible in DM, but I still think using the current name is less confusing. I'll let you know if we manage to find the tag/metadata whatever...

**Comment by mwalls** [comment] 2016-06-15 12:32
For completeness there is also the command  to change the **name** of image g to "test3", : g.imagesetname("test3"). This changes the name proposed when you save the file and the **title** in the window title bar. If you do it this way it's ok for hyperspy too. It seems only to be when you change it in Windows that the problem arises (but I will do further tests). But we still can't find the `metadata.General.title`  anywhere in our files using the latest DM.

**Comment by francisco-dlp** [comment] 2016-06-15 16:11
That makes sense. HyperSpy takes the title from the "Name" attribute in ``ImageDiplay-> Image -> Info``. The code is [here](https://github.com/hyperspy/hyperspy/blob/master/hyperspy/io_plugins/digital_micrograph.py#L547). From your explanation it seems that this is consistent with DM's behaviour. The issue seems to be that DM checks if Name was "manually" set and, if not, it displays the file name without actually modifying the Name attribute. Does it sound like a reasonable explanation? Still I don't know what we could do to make it less confusing for DM users in this case.

**Comment by mwalls** [comment] 2016-06-16 08:27
Maybe we're getting there. DM does change this attiribute the first time you try to look at it. Here's waht happens afaik.  A DM file "oldname" is renamed "newname" in Windows. If you open it in HS it is called oldname. If you open it again in DM it calls it newname in the display. If you immedialtely close it it will still be called oldname in HS. If you open it in DM and look at `ImageDislay>Image>Info`, it says newname and when you close the image is asks if you want to keep the changes, so it has changed the attribute. If you then open it in HS it is called newname.

As for what we should do, I don't see any reasonable objection to HS changing this attribute as soon as it finds it, since that's what DM itself does. Or at least just using the newname in the plot window, if you have scruples about changing the file. Maybe that's more difficult to arrange than I imagine?

**Comment by francisco-dlp** [comment] 2016-06-16 16:45
The problems is, how do we find out that the title mismatch is not due to the user manually setting the name attribute? I don't know how DM does it. Probably it gets the info from another attribute, but which one?

**Comment by mwalls** [comment] 2016-06-17 12:24
Well it seems not to be in the tags anywhere. The only way Marcel and I have found to access it is via `ImageDislay>Image>Info`, Which, as I say, is a Heisenberg type of observation! It changes the thing you're looking at (if it's different from the filename). I don't know how you can change it manually within DM without automatically changing the filename as well (i.e. the name displayed in the window title and the one proposed when you try to save it). DM seems to do everything it can to keep the two things the same. Maybe it's possible to save a file within DM with a name attribute different from the filename, but anyone capable of doing it would understand what was going on and in any case would not be surprised to see the filename as the plot window title in HS, if that was what HS decided to do. In fact I can't imagine anyone being surprised by a file plot being given its own fileneame as a name. But being given a recondite tag or attribute hidden somewhere in the DM metadata could cause confusion. In short, I'd still say the safe option is to display the filename in the windows.

**Comment by jat255** [comment] 2016-06-17 13:59
I have nothing of particular use to add to the conversation, but I'll note that "features" such as this that are relatively common in DM are one of the reasons I was so happy to have found HyperSpy :smile: 

In my experience with the names, I've always considered going into `ImageDisplay -> Image -> Info` the proper way to rename images in DM, since I consider the image name to be distinct from the file name, so I think I would be +1 on leaving the behavior the way it is. 

Alternatively, a compromise could be to title the window with the filename (stripped of extension) (i.e. `fig.canvas.set_window_title()`, while using the `metadata.general.title` value for the axis title (i.e. `<title> - Signal`. This may be a little confusing if the two are different, but at least a user would know that the right file was opened, and then they'd see that DM wasn't saving things the way they expected. This could be the "cover all our bases" approach, I suppose.

**Comment by tjof2** [comment] 2020-09-09 07:17
It sounds like the DM "feature" described above isn't necessarily desirable (modifying the data on loading then only warning about it when closing if you want to save changes).

Unless there's a demand to match this behaviour, I think closing is the correct course of action.

**Closed by tjof2** 2020-09-09 07:17 UTC
Labels: type: bug?
