### ISSUE TITLE
MemoryError: Unable to allocate 52.1 GiB for an array with shape (55956275200,) and data type uint8

### ISSUE THREAD

**Issue by laurasidsusana** [hyperspy/hyperspy#2853] opened 2021-11-15 12:31 UTC
Hello to everyone,
I have this error when trying to load a file from 4dstem measurements, but it gives me this error, saying to report it to hyperspy

---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-11-65f19fda85d7> in <module>
      1 #DF=hs.load("D:/4DSTEM/5_11_2021/08_SPIM_0.01nm_0.31ms_6bit_scan_110deg_LiveHADF.dm4")
----> 2 SPIM=hs.load("D:/4DSTEM/5_11_2021/08_SPIM_0.01nm_0.31ms_6bit_scan_110deg.dm4")

c:\users\susana\appdata\local\conda\conda\envs\py4dstem\lib\site-packages\hyperspy\io.py in load(filenames, signal_type, stack, stack_axis, new_axis_name, lazy, convert_units, escape_square_brackets, stack_metadata, load_original_metadata, show_progressbar, **kwds)
    421     else:
    422         # No stack, so simply we load all signals in all files separately
--> 423         objects = [load_single_file(filename, lazy=lazy, **kwds) for filename in filenames]
    424 
    425     if len(objects) == 1:

c:\users\susana\appdata\local\conda\conda\envs\py4dstem\lib\site-packages\hyperspy\io.py in <listcomp>(.0)
    421     else:
    422         # No stack, so simply we load all signals in all files separately
--> 423         objects = [load_single_file(filename, lazy=lazy, **kwds) for filename in filenames]
    424 
    425     if len(objects) == 1:

c:\users\susana\appdata\local\conda\conda\envs\py4dstem\lib\site-packages\hyperspy\io.py in load_single_file(filename, **kwds)
    474     try:
    475         # Try and load the file
--> 476         return load_with_reader(filename=filename, reader=reader, **kwds)
    477 
    478     except BaseException:

c:\users\susana\appdata\local\conda\conda\envs\py4dstem\lib\site-packages\hyperspy\io.py in load_with_reader(filename, reader, signal_type, convert_units, load_original_metadata, **kwds)
    494     """Load a supported file with a given reader."""
    495     lazy = kwds.get('lazy', False)
--> 496     file_data_list = reader.file_reader(filename, **kwds)
    497     signal_list = []
    498 

c:\users\susana\appdata\local\conda\conda\envs\py4dstem\lib\site-packages\hyperspy\io_plugins\digital_micrograph.py in file_reader(filename, record_by, order, lazy, optimize)
   1053                                     dtype=image.dtype)
   1054             else:
-> 1055                 data = image.get_data()
   1056             # in the event there are multiple signals contained within this
   1057             # DM file, it is important to make a "deepcopy" of the metadata

c:\users\susana\appdata\local\conda\conda\envs\py4dstem\lib\site-packages\hyperspy\io_plugins\digital_micrograph.py in get_data(self)
    664         if isinstance(self.imdict.ImageData.Data, np.ndarray):
    665             return self.imdict.ImageData.Data
--> 666         data = self._get_data_array()
    667         if self.imdict.ImageData.DataType in (27, 28):  # New packed complex
    668             return self.unpack_new_packed_complex(data)

c:\users\susana\appdata\local\conda\conda\envs\py4dstem\lib\site-packages\hyperspy\io_plugins\digital_micrograph.py in _get_data_array(self)
    642         if self.imdict.ImageData.DataType in (27, 28):  # Packed complex
    643             count = int(count / 2)
--> 644         data = np.fromfile(self.file,
    645                            dtype=self.dtype,
    646                            count=count)

MemoryError: Unable to allocate 52.1 GiB for an array with shape (55956275200,) and data type uint8

**Comment by din14970** [comment] 2021-11-15 13:28
You are trying to load 52.1 Gigabytes of information into your computer memory. It's highly likely that you computer doesn't have that much available RAM and so it throws an error. For these kinds of huge datasets you should use the `lazy=True` key word in the `load` function, which keeps the data on disk and only loads it into memory when necessary.

**Comment by ericpre** [comment] 2021-11-17 19:58
Indeed, as @din14970 have explained, there is a `MemoryError` and one solution is to process the data lazily. Closing for now, please re-open, if the issue is different.

**Closed as completed by ericpre** 2021-11-17 19:58 UTC
