### ISSUE TITLE
plotting with lazy loading

### ISSUE THREAD

**Issue by gwpaterson** [hyperspy/hyperspy#1765] opened 2017-10-19 18:20 UTC
When plotting lazy signals, the navigation image appears to be generated in-core, resulting in possible out-of-memory errors. Since lazy signals are immutable, I think we should be able to test if the signal is lazy, calculate the navigation image out-of-core (chunked), and store it for future use of plotting that signal without having to worry about updating it later. 

Some of this is discussed here: http://hyperspy.org/hyperspy-doc/current/user_guide/big_data.html#navigator-plot

**Comment by francisco-dlp** [comment] 2017-10-19 19:12
I think that the navigator should be computed lazily, are you sure that this is not the case?

Storing the navigator sounds like an excellent idea. Actually we could add a method e.g.``BaseSignal.set_navigator`` for that so that the user can do it manually for standard signals, and it could be performed automatically for lazy signals as you propose.

**Comment by gwpaterson** [comment] 2017-10-19 20:37
Looking in a little more detail, you may be right about calculating nav images from native hs files loaded lazily. The problem may be due to the way chunking is passed from our own file format.

**Comment by ericpre** [comment] 2021-01-29 20:01
Done in #1765.

**Comment by ericpre** [comment] 2021-02-05 09:55
The issue discussed seems to be related to situations where the chunking is inappropriate and calling the lazy signal through [`__call__`](https://github.com/hyperspy/hyperspy/blob/c373169bb3e73e3b8bd1bf7e3bec5dff39776a66/hyperspy/signal.py#L2530) trigger a large computation and huge memory usage and it looks like it compute the whole signal - which is not the case but possible as computational equivalent...

I believe this is a minimal example to reproduce:
```python
import dask.array as da
import hyperspy.api as hs
import numpy as np

chunks = (32, 32, 32, 32)
data = da.random.random((512, 512, 256, 256), chunks=chunks)
s = hs.signals.Signal2D(data).as_lazy()
s._make_lazy(rechunk=True)
s1 = s.T
s1()
```

While removing the rechunking step works as expected:
```python
import dask.array as da
import hyperspy.api as hs
import numpy as np

chunks = (32, 32, 32, 32)
data = da.random.random((512, 512, 256, 256), chunks=chunks)
s = hs.signals.Signal2D(data).as_lazy()
s1 = s.T
s1()
```

The plotting have been improved in #1765, so I will close this issue and continue in #2637 in order to narrow down the issue.

**Closed as completed by ericpre** 2021-02-05 09:56 UTC
Labels: type: enhancement, type: new feature
