### ISSUE TITLE
errors loading BCF files

### ISSUE THREAD

**Issue by jeinsle** [hyperspy/hyperspy#2244] opened 2019-08-30 11:11 UTC
I have been trying to import a series of EDS maps generated with Esprit version 2.1.  however, when I try to load this file (https://www.dropbox.com/s/iqmclr7fn871pek/Mapping_%281%2C1%29.bcf?dl=0) I get this error:
 ```python
KeyError                                  Traceback (most recent call last)
<ipython-input-6-ad1ad3391a64> in <module>
     ----> 1 b=hs.load('20190723_bon_accord_BCF_data/Mapping_(1,1).bcf')
     ~\AppData\Local\conda\conda\envs\hyperspy\lib\site-packages\hyperspy\io.py in 
 load(filenames, signal_type, stack, stack_axis, new_axis_name, lazy, convert_units, **kwds)
     279             objects = [load_single_file(filename, lazy=lazy,
    280                                         **kwds)
 --> 281                        for filename in filenames]
     282 
    283         if len(objects) == 1:`

 ~\AppData\Local\conda\conda\envs\hyperspy\lib\site-packages\hyperspy\io.py in 
 <listcomp>(.0)
 279             objects = [load_single_file(filename, lazy=lazy,
 280                                         **kwds)
 --> 281                        for filename in filenames]
     282 
     283         if len(objects) == 1:
 
 ~\AppData\Local\conda\conda\envs\hyperspy\lib\site-packages\hyperspy\io.py in 
 load_single_file(filename, **kwds)
     316     else:
     317         reader = io_plugins[i]
 --> 318         return load_with_reader(filename=filename, reader=reader, **kwds)
     319 
     320 
 
 ~\AppData\Local\conda\conda\envs\hyperspy\lib\site-packages\hyperspy\io.py in 
 load_with_reader(filename, reader, signal_type, convert_units, **kwds)
     323     lazy = kwds.get('lazy', False)
     324     file_data_list = reader.file_reader(filename,
 --> 325                                         **kwds)
     326     objects = []
     327 
 
 ~\AppData\Local\conda\conda\envs\hyperspy\lib\site- 
    packages\hyperspy\io_plugins\bruker.py in file_reader(filename, *args, **kwds)
        1189     ext = splitext(filename)[1][1:]
        1190     if ext == 'bcf':
     -> 1191         return bcf_reader(filename, *args, **kwds)
    1192     elif ext == 'spx':
   1193         return spx_reader(filename, *args, **kwds)
 
 ~\AppData\Local\conda\conda\envs\hyperspy\lib\site- 
packages\hyperspy\io_plugins\bruker.py in bcf_reader(filename, select_type, index, 
 downsample, cutoff_at_kV, instrument, lazy)
    1217 
    1218     # objectified bcf file:
 -> 1219     obj_bcf = BCF_reader(filename, instrument=instrument)
    1220     if select_type == 'spectrum':
    1221         select_type = 'spectrum_image'
 
 ~\AppData\Local\conda\conda\envs\hyperspy\lib\site- 
packages\hyperspy\io_plugins\bruker.py in __init__(self, filename, instrument)
     883         hd_bt_str = fix_dec_patterns.sub(b'\\1.\\2', header_byte_str)
     884         self.header = HyperHeader(
 --> 885             hd_bt_str, self.available_indexes, instrument=instrument)
     886         self.hypermap = {}
     887 
 
 ~\AppData\Local\conda\conda\envs\hyperspy\lib\site- 
packages\hyperspy\io_plugins\bruker.py in __init__(self, xml_str, indexes, instrument)
     586         self._set_images(root)
     587         self.elements = {}
 --> 588         self._set_elements(root)
     589         self.line_counter = interpret(root.find('./LineCounter').text)
     590         self.channel_count = int(root.find('./ChCount').text)
 
 ~\AppData\Local\conda\conda\envs\hyperspy\lib\site- 
packages\hyperspy\io_plugins\bruker.py in _set_elements(self, root)
     729                 self.elements[tmp_d['XmlClassName']] = {'line': tmp_d['Line'],
     730                                                         'energy': tmp_d['Energy'],
 --> 731                                                         'width': tmp_d['Width']}
     732         except AttributeError:
     733             _logger.info('no element selection present in the spectra..')
 
 KeyError: 'Width'`
```

I really do not understand what is the problem with the file. Further,  On a data set, I just took yesterday using a similar (presumably newer version of Esprit) I can load the data without error. (new data - https://www.dropbox.com/s/6cpjjzd4yzqczvd/gc2_1a_eds_map.bcf?dl=0). 

 the final piece to this puzzle is when I try to load this data set(https://www.dropbox.com/s/bqi8l4idppg45cl/E17_017.bcf?dl=0) taken before the first I get the following error:
`C:\Users\jeinsle\AppData\Local\conda\conda\envs\hyperspy\lib\site-packages\hyperspy\io_plugins\bruker.py:830: RuntimeWarning: overflow encountered in long_scalars
  real_time = line_cnt_sum * line_avg * pix_avg * pix_time * width / 1000000.0`

Overall, I get inconsistent loading behavior when working with bcf files, even if they are generated on the same system (files 1 and 3) or with the same version of esprit (all three files generated with Esprit version 2.1, but file 2 is specifically collected using ver 2.1.2.17921.).  the biggest difference between the three data sets is the file 1 was collected using the MAPS option for Esprit which allows for automated stitching of multiple EDS maps across a sample.

**Comment by sem-geologist** [comment] 2019-08-30 11:31
ok I have some simple solution for your error 1:
#2245 
It is that your map uses automatic energy width, and so KeyError is caused as `'Width'` field for elements in the XML header of bcf file is missing. The 'Width' of energy is not used in hyperspy, so the fix is to not try getting that field.

The last report with overflow is however intriguing. I am going to look into that.

**Comment by jeinsle** [comment] 2019-08-30 11:42
Ok that sounds promising long term, but a) is there an option in `hs.load()` that I should use that I do not see in the function documentation? or b) do I need to install a particular development branch?  sorry, but not deep in the depths of the development, just trying to get the tools to work for my experiments.

**Comment by sem-geologist** [comment] 2019-08-30 11:43
Hmm... I can't reproduce your `RuntimeWarning` (overflow) with E17_017.bcf - it is not producing warning on my system. Are you running it under Windows on 32 bit version?

**Comment by sem-geologist** [comment] 2019-08-30 11:52
@jeinsle, if you want to use it right now, and don't want to wait for package/patch/update be available, you can find your bruker.py plugin location independently from OS with:
```python
from hyperspy.io_plugins import bruker
bruker.__file__
```
Open the file at that filelocation with simple text editing program, move to lines 730-731 and remove `'width': tmp_d['Width']` part leaving the closing curl bracket intact. After restarting hyperspy it should just work with your bcf's.

It is however a hack - keep it in mind. I sure will be required to fix some failing tests for #2245 to get merged.

**Comment by jeinsle** [comment] 2019-08-30 12:02
> Hmm... I can't reproduce your `RuntimeWarning` (overflow) with E17_017.bcf - it is not producing warning on my system. Are you running it under Windows on 32 bit version?

I am 64 bit windows as far as I know......

**Comment by jeinsle** [comment] 2019-08-30 12:02
arggh.... did not mean to close.

**Comment by jeinsle** [comment] 2019-08-30 12:03
> Hmm... I can't reproduce your `RuntimeWarning` (overflow) with E17_017.bcf - it is not producing warning on my system. Are you running it under Windows on 32 bit version?

I am running a windows 64-bit system as far as I know.  kind of think that was required set up so we could use the RAM and graphics card this box has.

**Comment by sem-geologist** [comment] 2019-08-30 12:14
what about Hyperspy? it comes in 32 and 64 bits (or jupyter, if hyperspy is installed through it, it also is available as 32 and 64bit)

**Comment by jeinsle** [comment] 2019-08-30 12:26
> what about Hyperspy? it comes in 32 and 64 bits (or jupyter, if hyperspy is installed through it, it also is available as 32 and 64bit)
hmm would have thought 64 bit... I honestly never give this much thought.  How do I check this, as I always just hit install each time an install hyperspy/ anaconda on a new workstation?  Pretty sure i do 64 bit but.....

**Comment by jeinsle** [comment] 2019-08-30 12:28
the io hack works which is good as now I can at least play the real games I want to do with the data set.

**Comment by ericpre** [comment] 2019-08-30 15:08
> the final piece to this puzzle is when I try to load this data set(https://www.dropbox.com/s/bqi8l4idppg45cl/E17_017.bcf?dl=0) taken before the first I get the following error:
> ```
> C:\Users\jeinsle\AppData\Local\conda\conda\envs\hyperspy\lib\site-packages\hyperspy\io_plugins\bruker.py:830: RuntimeWarning: overflow encountered in long_scalars real_time = line_cnt_sum * line_avg * pix_avg * pix_time * width / 1000000.0
>```

This is runtime warning and not an error and it is fairly likely that the data loaded properly.

> Hmm... I can't reproduce your RuntimeWarning (overflow) with E17_017.bcf - it is not producing warning on my system. Are you running it under Windows on 32 bit version?

I don't have the warning on linux neither. Quite often, numpy raises false positive warning, which can be ignored but in this case it may be worth double checking if the type to the variable are not wrong.

**Closed as completed** 2019-09-06 09:06 UTC
Labels: type: bug, status: fix-submitted

**Comment by jeinsle** [comment] 2019-12-01 21:28
Hi again, so I am trying to load a BCF of an EDS file that I collected as part of a tomography run, and I am getting the following error (below).  I was about to try a similar hack to the Brucker file like above, but this does not seem like the correct way to proceed.  I think there are no elements selected by default, as I knew I would be adding them in during post-processing.


```
eds=hs.load('slice1_EDS/EDS - SliceImage - 001_Slice1.bcf',)
eds
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-19-9814a876e6d7> in <module>
----> 1 eds=hs.load('slice1_EDS/EDS - SliceImage - 001_Slice1.bcf')
      2 eds

~\AppData\Local\conda\conda\envs\cmeans\lib\site-packages\hyperspy\io.py in load(filenames, signal_type, stack, stack_axis, new_axis_name, lazy, convert_units, **kwds)
    279             objects = [load_single_file(filename, lazy=lazy,
    280                                         **kwds)
--> 281                        for filename in filenames]
    282 
    283         if len(objects) == 1:

~\AppData\Local\conda\conda\envs\cmeans\lib\site-packages\hyperspy\io.py in <listcomp>(.0)
    279             objects = [load_single_file(filename, lazy=lazy,
    280                                         **kwds)
--> 281                        for filename in filenames]
    282 
    283         if len(objects) == 1:

~\AppData\Local\conda\conda\envs\cmeans\lib\site-packages\hyperspy\io.py in load_single_file(filename, **kwds)
    316     else:
    317         reader = io_plugins[i]
--> 318         return load_with_reader(filename=filename, reader=reader, **kwds)
    319 
    320 

~\AppData\Local\conda\conda\envs\cmeans\lib\site-packages\hyperspy\io.py in load_with_reader(filename, reader, signal_type, convert_units, **kwds)
    323     lazy = kwds.get('lazy', False)
    324     file_data_list = reader.file_reader(filename,
--> 325                                         **kwds)
    326     objects = []
    327 

~\AppData\Local\conda\conda\envs\cmeans\lib\site-packages\hyperspy\io_plugins\bruker.py in file_reader(filename, *args, **kwds)
   1188     ext = splitext(filename)[1][1:]
   1189     if ext == 'bcf':
-> 1190         return bcf_reader(filename, *args, **kwds)
   1191     elif ext == 'spx':
   1192         return spx_reader(filename, *args, **kwds)

~\AppData\Local\conda\conda\envs\cmeans\lib\site-packages\hyperspy\io_plugins\bruker.py in bcf_reader(filename, select_type, index, downsample, cutoff_at_kV, instrument, lazy)
   1216 
   1217     # objectified bcf file:
-> 1218     obj_bcf = BCF_reader(filename, instrument=instrument)
   1219     if select_type == 'spectrum':
   1220         select_type = 'spectrum_image'

~\AppData\Local\conda\conda\envs\cmeans\lib\site-packages\hyperspy\io_plugins\bruker.py in __init__(self, filename, instrument)
    882         hd_bt_str = fix_dec_patterns.sub(b'\\1.\\2', header_byte_str)
    883         self.header = HyperHeader(
--> 884             hd_bt_str, self.available_indexes, instrument=instrument)
    885         self.hypermap = {}
    886 

~\AppData\Local\conda\conda\envs\cmeans\lib\site-packages\hyperspy\io_plugins\bruker.py in __init__(self, xml_str, indexes, instrument)
    586         self._set_images(root)
    587         self.elements = {}
--> 588         self._set_elements(root)
    589         self.line_counter = interpret(root.find('./LineCounter').text)
    590         self.channel_count = int(root.find('./ChCount').text)

~\AppData\Local\conda\conda\envs\cmeans\lib\site-packages\hyperspy\io_plugins\bruker.py in _set_elements(self, root)
    728                 tmp_d = dictionarize(j)
    729                 self.elements[tmp_d['XmlClassName']] = {'line': tmp_d['Line'],
--> 730                                                         'energy': tmp_d['Energy']}
    731         except AttributeError:
    732             _logger.info('no element selection present in the spectra..')

KeyError: 'XmlClassName'
```

**Comment by sem-geologist** [comment] 2019-12-02 20:59
@jeinsle I see, probably the version 2.1 files do something a bit different than 1.x. We got finally installed Esprit 2 on one of our SEM so I will probably produce different kind of files and will test it with bcf reader.

As for temporary hack around, try commenting out the 729 line `self.elements[tmp_d...`

**Comment by jeinsle** [comment] 2019-12-05 19:26
@sem-geologist  thanks for this.  Just kind of completely lost in that file.
> As for temporary hack around, try commenting out the 729 line `self.elements[tmp_d...`
