### ISSUE TITLE
Release v1.6.1

### ISSUE THREAD

**Issue by tjof2** [hyperspy/hyperspy#2490] opened 2020-08-21 11:41 UTC
Looking at the milestone: https://github.com/hyperspy/hyperspy/milestone/41, there's already a few important bugs fixed since the 1.6 release, including

- #2475 (histogram regression introduced in 1.6 that affects https://github.com/pyxem/pyxem/issues/620)
- #2479 
- #2484 
- #2487 

Is it worth a new patch release soon @francisco-dlp & @ericpre ?

**Comment by ericpre** [comment] 2020-08-21 12:09
Indeed, we should do patch release more often, which we could do if the release process was more automated.
With #2473, we can build and upload the wheel on pypi when pushing a tag. Another thing is that we should have something in place to generate the changelog easily. It would be good also to automate the upload of the doc to the website.

**Comment by tjof2** [comment] 2020-08-21 12:10
Is #2473 ready to go?

**Comment by ericpre** [comment] 2020-08-23 15:11
#2473 is now in good shape.
For further simplification of the release process, we should generate the release notes automatically and write it to the changelog of the user guide. It should also be fairly easy to update the github release with the github workflow introduced in #2473.

**Comment by francisco-dlp** [comment] 2020-08-24 13:47
#2473 is a big step towards decreasing the burden of releasing. As mentioned by @ericpre, the next steps are:

* automatic changelog generation, maybe with something like https://github.com/github-changelog-generator/github-changelog-generator?
* Automatic documentation generation and upload.

Other possible steps to consider:

* Automatic version bumping
* Remove version number from website
* Automatic update of the zenodo DOI on release.
* Closing the google group and stop advertising releases there (we haven't done it in a while anyway).
* Since the plan is to release more often, we could incorporate a beta release step in the workflow.

One issue introduced in #2473 that needs to be addressed is that, because a new release tag in GH triggers the generation of a new DOI, the wheels generated automatically will have the DOI of the previous version, and that's what will appear in the pypi page.

**Comment by ericpre** [comment] 2020-08-24 22:12
Indeed the DOI will need to be sorted. What do you think about doing the following:
1. a github release is created when pushing a tag
2. the Zenodo DOI is generated automatically following the creation of the Github release - this should be already the case
3. Get the DOI -> update the `README.rst` file (which will be included in the sdist for pypi) and push the change to the RnM branch
4. build the wheel, upload, etc

1 and 4 are done and 2 and 3 are missing.

Regarding the changelog, rather than generating it automatically from the commit history, we could fill an entry with each PR, when appropriate. When we release, the doc will be updated and after the release, we will need to change it again to make it ready for development.

**Comment by francisco-dlp** [comment] 2020-08-25 10:28
What about a simpler solution:

* Replace the specific doi with the concept one in readme—that one is permanent, so it doesn't need updating.
* Explain in the citing section of the UG that the concept DOI can be used to cite HyperSpy for general discussion of the project. However, the specific DOI must be used when a specific version of HyperSpy has been used to process data in order to ensure reproducibiliy. We could add a link to the [view all versions page](https://zenodo.org/search?page=1&size=20&q=conceptrecid:%22592838%22&sort=-version&all_versions=True).

**Comment by tjof2** [comment] 2020-08-25 10:30
https://doi.org/10.5281/zenodo.592838 always points to the latest version

> You can cite all versions by using the DOI 10.5281/zenodo.592838. This DOI represents all versions, and will always resolve to the latest one

**Comment by ericpre** [comment] 2020-08-25 10:36
Agreed, considering that there is no standard to include a DOI in a package, we can simply rely on the generic one and the link.

**Comment by francisco-dlp** [comment] 2020-08-25 13:04
See #2500

**Comment by francisco-dlp** [comment] 2020-08-25 14:54
Thinking about it, I am not convinced that using an automatic change log generator is a good idea: we'll gain in convenience but the change log risks being far less useful for users. What about simply adding a "update change list" item to the pull request checklist instead?

**Comment by ericpre** [comment] 2020-08-25 15:31
Yes, agreed! This is what I suggested above:

> Regarding the changelog, rather than generating it automatically from the commit history, we could fill an entry with each PR, when appropriate. When we release, the doc will be updated and after the release, we will need to change it again to make it ready for development.

And, it is good to keep things simple! Ideally it should be in a single file (for example `changelog_dev`) which we can easily insert at the top of the `CHANGES.rst`. Following this approach, we could do the following:
1. Check and edit the content of `changelog_dev` (_human action_)
2. push a tag (_human action_)
3. create the release, etc.
4. copy the `changelog_dev` to `CHANGES.rst`.
5. build distributions, test, publish to pypi, etc
6. reset the content of `changelog_dev`
7. set version to dev
8. push the doc changes to the repository (push to the correct branch! RnM or RnP)
9. publish the doc
10. update the website?

I am not very clear with how the doc is publish (not sure if the version matters, for example), so the last couple of steps may be wrong.

**Comment by ericpre** [comment] 2020-08-31 16:22
@francisco-dlp, do you think my last comment is a good plan?

**Comment by ericpre** [comment] 2020-09-01 17:20
In https://github.com/hyperspy/hyperspy_gui_traitsui/pull/31, I have added a script which covers points 4, 6-8 - still need some improvement to play well with the RnM, RnP branches. After this, the only thing left is to publish the doc after the release.

**Comment by tjof2** [comment] 2020-09-04 13:37
Pretty close to v1.6.1 right? This is the only thing left in the milestone.

**Comment by ericpre** [comment] 2020-09-04 14:18
I think it would be good to setup the semi-automatic release for 1.6.1.

**Comment by tjof2** [comment] 2020-09-10 09:50
Yes sounds good to aim for that!

**Comment by pc494** [comment] 2020-10-09 10:02
Hi all, is there anything I can do to help with this effort?

**Comment by thomasaarholt** [comment] 2020-10-09 10:08
Is there anything left? @ericpre, is something needed for semi-automatic release?

**Comment by ericpre** [comment] 2020-10-15 18:22
This PR is missing https://github.com/hyperspy/hyperspy/issues/2490#issuecomment-685012731 and @francisco-dlp review.

**Comment by ericpre** [comment] 2020-11-30 16:06
https://github.com/hyperspy/hyperspy/releases/tag/v1.6.1

**Closed as completed by ericpre** 2020-11-30 16:06 UTC
