### ISSUE TITLE
issue in signal module  in python3 with a .decode()

### ISSUE THREAD

**Issue by ggoret** [hyperspy/hyperspy#992] opened 2016-05-12 12:41 UTC
While loading a stack of hdf5 file, an error has been raised in the signal module in python with Hyperspy version 0.8.4 : 

 ---------------------------------------------------------------------------
```python
AttributeError                            Traceback (most recent call last)
<ipython-input-62-804b198d1f51> in <module>()
----> 1 stack = hs.load('my_file.hdf5', signal_type = 'EDS_TEM',stack = True, stack_axis_name = 'Tilts', mmap = True)

/home/prog/python-el6/python-3.5.1/lib/python3.5/site-packages/hyperspy/io.py in load(filenames, record_by, signal_type, signal_origin, stack, stack_axis, new_axis_name, mmap, mmap_dir, **kwds)
    194                 )[1]
    195             messages.information('Individual files loaded correctly')
--> 196             signal._print_summary()
    197             objects = [signal, ]
    198         else:

/home/prog/python-el6/python-3.5.1/lib/python3.5/site-packages/hyperspy/signal.py in _print_summary(self)
   2807     def _print_summary(self):
   2808         string = "\n\tTitle: "
-> 2809         string += self.metadata.General.title.decode('utf8')
   2810         if self.metadata.has_item("Signal.signal_type"):
   2811             string += "\n\tSignal type: "

AttributeError: 'str' object has no attribute 'decode'
```
 ---------------------------------------------------------------------------
replacing the line 2809 in signal.py by : 
```python
string += self.metadata.General.title #.decode('utf8')
```
seems to fix the issue.

Thanks

Gael

**Comment by francisco-dlp** [comment] 2016-05-12 14:23
@ggoret, thank you for reporting the issue and the workaround. This is a duplicate of #924, fixed in #925.

**Closed by francisco-dlp** 2016-05-12 14:23 UTC
