### ISSUE TITLE
HyperSpy doesn't start properly when WX >=3 and traitsui <= 4.4

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#435] opened 2015-01-18 17:49 UTC
I develop primarily using windows, but I have arch linux installed on my laptop and have been trying to use hyperspy while traveling. With the latest pushes to the master branch, I have noticed that I cannot run a notebook without the kernel crashing repeatedly. I do not have this problem on my Windows machine. 

I've isolated the problem to a commit (a87685b918bbd283b7893d56e25ce1b451567d4d) adding traits to the component class. The behavior is very strange as there is no output to the JS console, or to the bash console, other than the following: https://gist.github.com/jat255/d4b6347cf3b717b2a532.

To diagnose this, I completely deleted my local files, cloned the repo fresh, and went commit by commit, doing a hard reset of my working tree to each one, and this commit is the first one that causes the crash. It occurs only when opening an existing or creating a new notebook. i.e. there are no errors when the server is started or when it is not serving any notebooks. I am not sure why this error is not seen when running on windows. The related packages are the same on each system (as shown through pip) and are the following:

1. ipython: 2.4.0-maint (installed through pip -e ./ from github)
1. traits: 4.5.0 (latest version, installed through package manager in linux, and through python(x,y) on windows)
1. traitsui: 4.40 (latest version, same as above)

Is there any way I could go about debugging this further and figuring out the reason for the kernel crashing? I'm not sure how to get more output beyond 

    2015-01-18 12:35:31.022 [NotebookApp] WARNING | KernelRestarter: restart failed

**Comment by jat255** [comment] 2015-01-18 17:51
I should also note that starting a pure `ipython notebook` does not cause any sort of crash, and I made sure to delete `~/.ipython` and `~/.hyperspy` before testing.

**Comment by jat255** [comment] 2015-01-18 18:02
I was able to run ipython in debug mode, which gave me the following output:
https://gist.github.com/jat255/bc5319f5550558ff9b3f

The context right around the crash is the following:

```javascript
[IPKernelApp] Enabling GUI event loop integration, eventloop=qt, matplotlib=Qt4Agg
[IPKernelApp] Loading IPython extensions...
[IPKernelApp] Loading IPython extension: storemagic
[IPKernelApp] Running code from IPythonApp.exec_lines...
[IPKernelApp] Running code in user namespace: from hyperspy.hspy import *
[IPKernelApp] Running code in user namespace: import hyperspy.Release
[IPKernelApp] Running code in user namespace: print hyperspy.Release.info
[IPKernelApp] entering eventloop <function loop_qt4 at 0x7fe271a47050>
[IPKernelApp] 
*** MESSAGE TYPE:kernel_info_request***
[IPKernelApp]    Content: {}
   --->
   
[IPKernelApp] {'parent_header': {u'username': u'username', u'msg_id': u'3982999497CD4613AFE54A66FEC9E607', u'msg_type': u'kernel_info_request', u'session': u'3D6296224269420DB1EB2FA1F24B5CE9'}, 'msg_type': 'kernel_info_reply', 'msg_id': 'e61933b3-7e4d-4565-bc0e-3d6223f94f65', 'content': {'protocol_version': [4, 1], 'language_version': [2, 7, 9], 'language': 'python', 'ipython_version': [2, 4, 0, 'maint']}, 'header': {'date': datetime.datetime(2015, 1, 18, 12, 52, 58, 653767), 'username': u'kernel', 'session': u'0be76d04-3b2d-458a-a984-0994d37b52a7', 'msg_id': 'e61933b3-7e4d-4565-bc0e-3d6223f94f65', 'msg_type': 'kernel_info_reply'}, 'tracker': <zmq.sugar.tracker.MessageTracker object at 0x7fe28f9d0b50>, 'metadata': {}}
2015-01-18 12:53:00.782 [NotebookApp] Polling kernel...
2015-01-18 12:53:00.783 [NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 7357594a-54d9-4bc6-b266-a7e514b23d05 restarted
```

**Comment by magnunor** [comment] 2015-01-18 18:07
To add a datapoint: I can not replicate this bug in Ubuntu 14.10, using the current master.

**Comment by vidartf** [comment] 2015-01-18 23:06
It's a shot in the dark, but I know Qt can be a bit sensitive sometimes. Could you check your traits toolkit?
```python
from traits.etsconfig.api import ETSConfig
print ETSConfig.toolkit
```
Since you use qt4 for MPL, I'd expect the value to be 'qt4'. Then again, traits is already used in hyperspy, so the only thing this should change is the order of imports and some other uses. Could you maybe add some debug output lines somewhere in component.py and see if you can trace down which line is the last to execute successfully? I.e. around the definitions and imports, not in the function definitions (I'd think). If ```print``` doesn't work then maybe raising an exception will, as it halts further execution in that module.

**Comment by francisco-dlp** [comment] 2015-01-19 12:26
I cannot reproduce the bug in Debian testing using both the system Python and anaconda.

**Comment by jat255** [comment] 2015-01-19 14:38
Thank you all for the quick feedback. After a little more testing, it appears that the kernel will crash using any method of running hyperspy (I tried notebook, console, and qtconsole). 

@vidartf, as you suspected, the ETSConfig.toolkit value was 'qt4'. I tried changing the toolkit to see the results. Using `gtk` or `None` gave the same result. Using `wx` or `tk` allowed a notebook to load, but hyperspy was not running correctly, as I could not create a signal, or load a DM3 file (the load() method was not correctly overloaded by hyperspy, and complained not being able to load the DM3 file as a pickle). 

Trying to load `hspy.py` gave a little more information, resulting in the following `VersionError` when loading with the `wx` toolkit: https://gist.github.com/jat255/11ce8066d4142d4f455d and the following `AlreadyImportedError` whn loading with the `tk` toolkit: https://gist.github.com/jat255/bb2dc3d189e86aa7b8c3. The errors are identical except for the very last line.

Going through component.py with print statements (as suggested by @vidartf) leads me to the same result as shown in the gists linked above. What is interesting though, is that I added a print line into `/usr/lib/python2.7/site-packages/traitsui/toolkit.py` (line 93 of the gist) to `print toolkit_name`, and it returned `wx`, even though I specified `--toolkit qt4` on the command line.

**Comment by jat255** [comment] 2015-01-19 14:50
Suspecting this to be ultimately an issue with the wxpython installation on my machine, I removed all the packages I could find relating to wxpython, and the code began to work as expected. I could run a notebook or console session without any problems.

I then proceeded to install wxpython2.8 from the Arch Linux extra repository. This also pulled in the wxpython (v3.0.2.0-1) package as a dependency. Running the same code again, the notebook failed at the same step, so there appears to be an incompatibility between traitsui and these versions of wxpython.

Oddly enough I was also unable to install wxpython through `pip`, even though the package showed up using `pip search`. I kept getting errors such as 

    Could not find any downloads that satisfy the requirement wxPython

Regardless, the most recent code base does appear to work on Arch Linux if you do not have wxpython installed. It appears this is an issue with traits, and not Hyperspy, but I suppose it would be good to make a note of this in the documentation?

**Comment by francisco-dlp** [comment] 2015-01-19 14:58
Yes, I think that the current traitsui does not support wx 3. However, I don't see why having wx 3 installed in your system should break traitsui when using a different toolkit. Probably it is worth to report the issue to the [traitsui developers](enthought/traitsui
).

**Comment by jat255** [comment] 2015-01-19 17:56
Perhaps we could modify `component.py` in such a way that it will work with qt4, even if wx 3 is installed. That should prevent most users from ever seeing this strange behavior. 

I added the following code to the beginning of component.py:
```python
import traits.etsconfig.etsconfig
from traits.etsconfig.api import ETSConfig
import hyperspy.defaults_parser as default

print "Toolkit from ETSconfig is: " + repr(ETSConfig.toolkit)
print "Toolkit from traits.etsconfig.etsconfig.ETSConfig.toolkit is: " + repr(traits.etsconfig.etsconfig.ETSConfig.toolkit)
print "Toolkit from hyperspy.defaults_parser.current_toolkit is: " + repr(default.current_toolkit)
```

Regardless of which toolkit I choose when starting from the command line, I get the following output, showing that the toolkit value is null, which is why it proceeds to loop through the possible toolkit values (https://github.com/enthought/traitsui/blob/master/traitsui/toolkit.py#L96-L137), generating an error when it gets to `wx`, if wx 3 happens to be installed:
```
Toolkit from ETSconfig is: ''
Toolkit from traits.etsconfig.etsconfig.ETSConfig.toolkit is: ''
Toolkit from hyperspy.defaults_parser.current_toolkit is: 'qt4'
```

This is unexpected (to me, at least) because of the following code in bin/hyperspy, which appears to set the `traits.etsconfig.etsconfig.ETSConfig.toolkit` value to `qt` or `wx`, but it appears that it does not persist to the time when component.py is executed:
https://github.com/hyperspy/hyperspy/blob/master/bin/hyperspy#L172-L176

**Comment by jat255** [comment] 2015-01-19 17:56
I've also discovered that if I explicitly set the toolkit in `component.py` by adding the following lines to the beginning
```python
from traits.etsconfig.api import ETSConfig
ETSConfig.toolkit = 'qt4'
````
then the code works as expected, and everything is fine. Is there someway to check the current toolkit from `component.py`, and if it is qt4 (which is probably most people's default), explicitly set the ETSConfig value? This (albeit ugly) patch would ensure that the code runs okay if wx 3 is installed.

**Comment by francisco-dlp** [comment] 2015-01-20 13:06
I still think that this is a traits bug. In my system `bin/hyperspy` sets the toolkit correctly. This is the output that I get adding your debugging lines to `component.py`:

```
hyperspy --toolkit qt4

Toolkit from ETSconfig is: 'qt4'
Toolkit from traits.etsconfig.etsconfig.ETSConfig.toolkit is: 'qt4'
Toolkit from hyperspy.defaults_parser.current_toolkit is: 'qt4'
```

```
hyperspy --toolkit wx

Toolkit from ETSconfig is: 'wx'
Toolkit from traits.etsconfig.etsconfig.ETSConfig.toolkit is: 'wx'
Toolkit from hyperspy.defaults_parser.current_toolkit is: 'wx'
```

```
hyperspy --toolkit gtk

Toolkit from ETSconfig is: 'null'
Toolkit from traits.etsconfig.etsconfig.ETSConfig.toolkit is: 'null'
Toolkit from hyperspy.defaults_parser.current_toolkit is: 'gtk'
```

```
hyperspy --toolkit tk

Toolkit from ETSconfig is: 'null'
Toolkit from traits.etsconfig.etsconfig.ETSConfig.toolkit is: 'null'
Toolkit from hyperspy.defaults_parser.current_toolkit is: 'tk'
```

```
hyperspy --toolkit None

Toolkit from ETSconfig is: 'null'
Toolkit from traits.etsconfig.etsconfig.ETSConfig.toolkit is: 'null'
Toolkit from hyperspy.defaults_parser.current_toolkit is: 'None'
```

**Comment by jat255** [comment] 2015-01-20 14:40
Hmm... That is very interesting. On my Windows computer (back at work), I obtain the same results as you, @francisco-dlp. 

Can you test running with `hyperspy console --toolkit qt4` and then pressing enter after hyperspy is loaded?

On the Arch machine that has the issue, running simply `hyperspy --toolkit qt4` works as expected and gives this output:
```
arch-E7240$ hyperspy --toolkit qt4
Toolkit from ETSconfig is: 'qt4'
Toolkit from traits.etsconfig.etsconfig.ETSConfig.toolkit is: 'qt4'
Toolkit from hyperspy.defaults_parser.current_toolkit is: 'qt4'
```

If I run `hyperspy console --toolkit qt4`, I get the following (after pressing enter at the first empty prompt):
```
arch-E7240$ hyperspy console --toolkit qt4
Toolkit from ETSconfig is: ''
Toolkit from traits.etsconfig.etsconfig.ETSConfig.toolkit is: ''
Toolkit from hyperspy.defaults_parser.current_toolkit is: 'qt4'
kernel died, restart ([y]/n)?
```

On my Windows machine, I get the following two results:
```
win-s30$ hyperspy --toolkit qt4
Toolkit from ETSconfig is: 'qt4'
Toolkit from traits.etsconfig.etsconfig.ETSConfig.toolkit is: 'qt4'
Toolkit from hyperspy.defaults_parser.current_toolkit is: 'qt4'
```

```
win-s30$ hyperspy console --toolkit qt4
Toolkit from ETSconfig is: ''
Toolkit from traits.etsconfig.etsconfig.ETSConfig.toolkit is: ''
Toolkit from hyperspy.defaults_parser.current_toolkit is: 'wx'
```

This suggests that maybe it is an issue with how `bin/hyperspy` is parsing the input? Or maybe when a session is started with `console`, `qtconsole`, or `notebook` options, traits loses track of the value that is specified on the command line, somehow?

**Comment by francisco-dlp** [comment] 2015-01-20 15:45
That's very interesting, when I run `hyperspy console --toolkit qt4` I do get the same wrong behavior as you. I see no reason why this should be the case, but, at first sight, there is nothing wrong with the `hyperspy` script.

I must admit that I am tired of the fact that the interactions between traitsui, matplotlib and IPython keep on breaking HyperSpy.

There are several things to consider:

* Currently using HyperSpy as a library is cumbersome when using the Qt backend because MPL likes to set the API to 1 while traitsui requires API 2. A workaround is to import hyperspy before starting matplotlib. However, I'm sure that many people get hit by this when they first try HyperSpy, what is certainly discouraging.
* In IPython 3.0 the pylab flag will be gone. We could workaround this by setting the environment in the HyperSpy profile, but do we really want to do this?
* HyperSpy does not support Python 3 because traits and traitsui are holding us back. I know that traits 4.5 finally supports Python 3, but not traitsui AFAIK.

What do you think about the following two proposals:
* Stop using traitsui. The few windows in HyperSpy could be replaced by IPython widgets when running in the notebook.
* Stop distributing the `hyperspy` script and encourage to users to import hyperspy using `import hyperspy as hs` instead.

**Comment by jat255** [comment] 2015-01-20 15:59
While I'm disheartened to hear that this is a more pernicious problem, I'm glad that it's not just my crazy machine causing the issues! It is certainly discouraging to have to work around so many issues with the external dependencies.

As for your proposals:
 * I think that (if it is not incredibly difficult), removing the dependence on traitsui would be beneficial. It would remove one more external dependency that could potentially cause problems. Is there another UI package that could replace it, or would the interactive features only be available when running in an IPython notebook?
 * I think that the `hyperspy` script is relatively important, as `hyperspy notebook` is I think how most users would start the program (or maybe that's just me...) It appears that using just `hyperspy` to start works correctly, but the problem is introduced with using `hyperspy <notebook, console, etc.>`

Another question:
 * I am not familiar with the history of development in hyperspy, so forgive me if this is obvious, but is there a reason why so many different toolkits/backends are supported? Since qt4 is truly cross-platform (and is already the default), it seems like just using that suite of tools would simplify things a great deal. Perhaps the others (which seem to be causing the problem here) could be removed.

**Comment by francisco-dlp** [comment] 2015-01-20 17:52
When we started HyperSpy back in 2007—it was called EELSLab at the time—it wasn't clear that Qt was going to become the toolkit of choice for multi-platform development, and that is why we decided to support several toolkits using traitsui. Today, as you suggest, supporting only Qt and doing it well would be a better choice. However, given that @vidartf is working in a Qt GUI, HyperSpyUI, I think that it makes sense to have a toolkit-free HyperSpy kernel that relies only on IPython widgets for interactivity and doesn't depend on traits.

Regarding the `hyperspy` script, its main purpose is to set up properly mpl, traits and ipython so that they work together smoothly. However, if we remove traitsui, I think that the script will no longer be necessary. Of course, using hyperspy will then become more verbose:

1. start IPython
2. import hyperspy.hspy as hs
3 %matplotlib qt

But this may actually be a good thing, especially for new users who are not familiar with Python.

These are drastic changes, so we should discuss this thoroughly. Any more opinions?

**Comment by jat255** [comment] 2015-01-20 18:40
I agree that an eventual separation of Hyperspy (as a kernel) and HyperspyUI is ideal. I've looked at a few examples of the interactive IPython widgets, and I agree that it seems as though most of the current gui components (I'm thinking of spike removal, background removal, preferences dialogue, etc.) could be implemented this way. 

As for the `hyperspy` script, I agree that learning to use Hyperspy as a library might be beneficial to new users (helping them see what's going on "behind the scenes", so to speak). I wonder then, would you also propose getting rid of the Hyperspy IPython profile that currently takes care of some of this?

**Comment by vidartf** [comment] 2015-01-24 02:23
From what I've been able to debug, this bug only appears when components.py is imported before the toolkit is set. Currently, components.py is imported in IPython startup (from hyperspy.hspy import * in IPython profile). This is after the script is run, but I think the main problem is that the script sometimes launches a new instance of python, dropping the previous context (or is somehow isolated from outside context). Could you try adding the line:
```python
import hyperspy.gui as _
```
early in hspy.py ? I added it right after the version import. "hyperspy.gui.\__init\__.py" already has code to set traits toolkit from matplotlib toolkit.

**Comment by francisco-dlp** [comment] 2015-01-27 12:14
Probably this could solve the problem (@jat255, did you try it?). However, the reason why the code to initialize the toolkit is in "hyperspy.gui.__init__.py" instead of "hyperspy.__init__.py" is that we intended to separate the gui code from the kernel, so that it only gets imported when the user needs it. At present this separation is broken in some few places, and "hyperspy.gui" does get imported when imported hspy, but this is a bug that should be fixed. @vidartf, would it be possible not to import traitsui in component.py?

**Comment by vidartf** [comment] 2015-01-27 14:44
If ```hyperspy.gui``` gets imported when ```hspy``` is imported, then it is currently done in the wrong order w.r.t. ```component```. Regarding the removal of traitsui from ```component``` (I see the argument for separation), it is only there to define the default editor, as traitsui will bug out trying to figure one out on its own (for that one complex type). So, if we remove it, the user of the code will always have to specify the editor, or have it raise an exception. That can work for me, but it is of course not ideal w.r.t future use by others.

Regarding ditching traits(ui) completely, it could work to replace traits with our own implementation (most important feature of traits is change notification). To replace the type/range checking of traits might be "a bit" more complex, but it might not be necessary? Replacing traitsui with our own implementation is not something I'd recommend, as the editor selection + type/value checking mechanics are rather complex (and I'd suggest keeping the core backend independent). If a suitable replacement can be found in another library, that might be worth looking into.

**Comment by jat255** [comment] 2015-01-27 21:31
@francisco-dlp, adding the line as @vidartf suggested before the version import does solve the problem.

**Comment by francisco-dlp** [comment] 2015-07-23 09:49
@jat255, does #584 fix this issue?

**Comment by jat255** [comment] 2015-07-26 15:51
Yes, it does!

Coincidentally, an upgrade of the `python2-traitsui` package on arch to version `4.5.1-1` also seemed to resolve this issue, which is why I didn't realize that I wasn't really seeing it anymore. (The arch package was upgraded on 2015/06/05).

To summarize, I can confirm that on the current `master` branch:
 * Kernel automatically dies when using `traitsui v4.4.0-1`
 * Kernel survives and runs fine when using `traitsui v4.5.1-1`

On the current `0.8.x` branch:
 * Kernel survives and runs okay when using either version of `traitsui`

**Closed** 2015-07-26 15:51 UTC
Labels: bug
