### ISSUE TITLE
DLL load failed: The specified procedure could not be found

### ISSUE THREAD

**Issue by Sputn1k7** [hyperspy/hyperspy#1731] opened 2017-09-13 21:52 UTC
Hi all,
    I am attempting to run HyperSpy through a CallExternalCommand activity in some automation SW. I am getting an error when importing HyperSpy, specifically the io_plugins\emd.py

The error message happens when registering the converter. The actual error is:

ImportError: DLL load failed: The specified procedure could not be found.

I do not use the .emd plugin, and I'm wondering if I can actively select which libraries to load from HyperSpy, or if I should just delete some .py files of things that throw errors that I do not use.

Any tips would be appreciated.

**Comment by francisco-dlp** [comment] 2017-09-14 07:11
You could edit [this line](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/io_plugins/__init__.py#L26) to disable the IO plugins that you don't want to load. It seems that the issue is the h5py library.

**Comment by Sputn1k7** [comment] 2017-09-18 22:45
Works great, thanks! Should I keep this open as a reminder to look at the h5py library? Or open a different issue? I'm not enitrely sure what the problem is (being a newbie to Python and Hyperspy)

**Comment by francisco-dlp** [comment] 2017-09-19 09:13
Thanks for the feedback. I'll close it since this is not a hpsy issue.

**Closed as completed by francisco-dlp** 2017-09-19 09:13 UTC
