### ISSUE TITLE
remove_background dialogue box disappearing

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#726] opened 2015-09-17 15:44 UTC
Sometimes when using the s.remove_background function with EELS spectra , the dialogue box disappears when moving the span selector. I have not tried with other kinds of spectrum types.

I can only make it disappear when using the power law background. Gaussian, offset or polynomial does not seem to be affected.

I'm not really sure exactly what triggers the dialogue box to disappear, but some of the GUI wizards might be able to fix this :)

**Comment by jat255** [comment] 2015-09-17 15:52
This is something I have noticed as well. It occurs only when using the Qt4 backend. I did some initial testing in this issue (https://github.com/hyperspy/hyperspy/issues/561). The eventual resolution of that issue solved the problem of the GUI not ever closing, but did not fix the problem that it sometimes disappears too soon.

My feeling is that it is likely some sort of silent failure that the traits ui doesn't understand how to handle, so it just closes without any error. That's just a gut feeling though, so I don't have any proof :smile:

**Comment by magnunor** [comment] 2015-09-17 16:02
I knew someone else had mentioned that earlier :) Just didn't find the correct Issue. 

I'm suspecting it has something to do with estimate_parameter in the [powerlaw component](https://github.com/hyperspy/hyperspy/blob/master/hyperspy/_components/power_law.py#L83), since I'm only able to replicate it with the power law background.

**Comment by francisco-dlp** [comment] 2016-02-08 17:32
I have submitted some fixes to the remove background code in #858 but, unfortunately, they don't fix this issue. The windows simply disappear without printing any exception, so it is difficult to find a fix without knowing the cause. This issue affect only the QT toolkit and has appeared recently, possibly due to changes in external libraries e.g. traitsui, Qt, pyside...

Unless someone is knows the cause of this problem, I suggest to change the milestone to 0.9.

**Closed** 2016-03-02 15:05 UTC
Labels: bug

**Comment by vidartf** [comment] 2016-03-02 16:25
Was this supposed to be closed automatically?

**Comment by dnjohnstone** [comment] 2016-05-23 11:03
What are we doing with this? Is it going to be a 0.8.5 job or has it been resolved over time?

**Comment by francisco-dlp** [comment] 2016-05-23 11:06
Unless someone knows how to fix it, we'll leave this open and release `0.8.5` anyway.

**Comment by jat255** [comment] 2017-05-05 12:03
I just noticed this issue again today...

**Comment by francisco-dlp** [comment] 2017-05-05 12:19
Yes, it has never gone. This issue affects only the Qt4 backend with recent versions of traitsui.

**Comment by jat255** [comment] 2017-05-05 12:27
It seems as though if you change the fitting method to Gaussian, it doesn't crash (like @magnunor said), but then also if you switch back to Power Law, it still doesn't crash...

Update: you don't even have to draw on the plot at all to get this to work. I wonder if we could programmatically switch the background calculation method to Gaussian and then back to Power Law, if that would still work. A messy workaround for sure, but this is a really annoying problem.

Update 2: It also appears that if you change the fitting method at all, subsequent calls to `remove_background` will not crash, either.

**Comment by francisco-dlp** [comment] 2017-05-05 12:53
Interesting! It may be that the runtimeerror is destabilizing the window somehow.

**Comment by jat255** [comment] 2017-05-05 12:54
Actually, now that I test it more, I don't think it's the case. It's so strange that sometimes it crashes right away, and then other times takes a lot of manipulation to crash.

**Comment by francisco-dlp** [comment] 2017-05-05 13:02
Yes, I've seen other windows (not only the remove_background one) crashing. I think that all the one that crash have in common that they include a span selector in the figure. We must be triggering a race condition.

**Comment by jat255** [comment] 2017-05-05 13:11
I think  the issue is in `powerlaw.estimate_parameters()`. Trying to hunt it down now

Update: Looks like it might be in the `integrate1D` calls in that method

**Comment by jat255** [comment] 2017-05-05 15:40
@francisco-dlp So I couldn't find the exact reason for failure, but I believe I've isolated it to the integration done in the [two-area method](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/_components/power_law.py#L123-L124).

I tried to change the estimating to a scipy-based method. It's about 10ms faster per iteration, and is giving reasonable values for `A` and `r`, but for some reason is not working when running interactively.  The relevant code is in a new branch [here](https://github.com/jat255/hyperspy/blob/BUGFIX_remove_background_gui_workaround/hyperspy/_components/power_law.py#L118-L130). If you have some time, could you take a look?

**Comment by francisco-dlp** [comment] 2017-05-05 16:26
@jat255, the purpose of the ``estimate_parameters`` method is to provide an estimation that is i) faster to run than nlls ii) more robust as nlls is sensitive to the starting parameters. It's likely that ii) is the reason why your code doesn't work interactively.

**Comment by jat255** [comment] 2017-05-05 17:00
I think you're right about the starting parameters bit. It's strange though, because when I put in some print statements, the fitting works once the selected window is large enough; it just doesn't draw a line on the interactive plot, presumably because there was an error when first dragging because the window is too narrow. I wonder if there would be some way around this (assuming this workaround works at all for the whole closing window thing).

Interestingly enough though, the `scipy.optimize.curve_fit` only takes about 16ms on my machine, compared to about 27 ms for the two-area method (timed using the `%%timeit` method).

**Comment by wohe157** [comment] 2022-11-21 14:24
Hi, I am using v1.7.3 on Windows 11 and I am still noticing this issue, is there a fix or workaround available?

**Comment by ericpre** [comment] 2022-11-29 19:19
Sadly, there is not much we can do from our side because there is no error and it is not reproducible, therefore it is extremely difficult to figure out where it comes from. I had a look at this in the past and there is nothing suspicious from our side...
