### ISSUE TITLE
Windows gui-traitsui missing on conda-forge

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1670] opened 2017-06-16 23:27 UTC
I suspect this is already known, and that there is some reaso that it isn't available on conda forge, but in case not:

Windows, python 3.6:

```bash
(py36) C:\Users\Me>conda install hyperspy-gui-traitsui -c conda-forge
Fetching package metadata .............

PackageNotFoundError: Package missing in current win-64 channels:
  - hyperspy-gui-traitsui
```

**Comment by francisco-dlp** [comment] 2017-06-17 08:04
This is known, but it's certainly a good idea to open an issue about it. The issue is that https://github.com/conda-forge/staged-recipes/pull/3044 has not been merged yet.

**Comment by jan-car** [comment] 2017-06-21 09:08
Good to see that it's not a problem on my side. I only got ```conda install hyperspy-gui-ipywidgets``` to work. Installing the traitsui GUI elements with pip still works (I'm on a Windows machine).

I'm not sure if this is the right place to ask, but as far as I understood, I only need either the ipywidgets or traitsui GUI, right?
If it wasn't for mayavi, which also uses traitsui, I would like to switch to PyQt5 (and subsequently to Python 3.6) in my projects completely, so I really like the option to circumvent traitsui in HyperSpy. Is there a way to suppress the error warning for the missing traitsui GUI elements, though?

**Comment by thomasaarholt** [comment] 2017-06-21 09:11
You are correct in that you only need one or the other.

If you are concerned with removing the warning only on your own machine, you could comment out lines 14 and onwards in `hyperspy/api.py`.

**Comment by francisco-dlp** [comment] 2017-06-21 09:43
conda-forge/staged-recipes#3044  has been merged, so this is no longer an issue.

**Closed as completed by francisco-dlp** 2017-06-21 09:43 UTC

**Comment by jan-car** [comment] 2017-06-21 17:30
Thanks for the quick answer, I'll think about commenting out the appropriate lines.
