### ISSUE TITLE
new+bug-fix: unify rectangle ROI and roi arguments in functions

### ISSUE THREAD

**Issue by sem-geologist** [hyperspy/hyperspy#2059] opened 2018-09-18 20:23 UTC
I want address few issues here connected with different roi arguments and ROI objects.
1. roi arguments in hyperspy functions lacks of consistency, once it expect top bottom and the left right, while in other functions it asks for left right and then top bottom (i.e. crop_image, align2D).
2. However, it would be nice if for roi argument in functions, the real interactive rectangular ROI object could be used, as alternative to tuple, or rectangular ROI object would have method to return unified tuple for roi (useful in the functions requiring roi).

## currently found bugs:
- `estimate_shift2D` function have wrong docstring describing the tuple for roi, which if following it results in wrong roi (which leads to poor performance of alignment), or fails the function as roi gets out of image bounds.
- Line2DROI().interactive() is broken

**Comment by ericpre** [comment] 2021-01-07 17:37
Duplicate of https://github.com/hyperspy/hyperspy/issues/1227, closing this one to keep the discussion in https://github.com/hyperspy/hyperspy/issues/1227.

**Closed as completed by ericpre** 2021-01-07 17:37 UTC
