### ISSUE TITLE
Stdout is polluted with progress bars

### ISSUE THREAD

**Issue by uellue** [hyperspy/hyperspy#1842] opened 2018-02-21 09:18 UTC
When working on analyzing the scaling behavior of excessive dask overheads (Issue #1840) as a function of the input data size, I came across two surprising and annoying behaviors of the compute() method. http://hyperspy.org/hyperspy-doc/current/api/hyperspy._signals.html?highlight=lazysignal#hyperspy._signals.lazy.LazySignal.compute

Current behavior: The compute() method displays a progress bar by default. The progress bar is written to stdout. This output got mixed with the actual benchmarking data that I was writing to stdout.

Expected behavior: The compute() method is quiet by default, at least when running in a script. The progress bar is written to stderr.

**Comment by francisco-dlp** [comment] 2018-02-21 09:29
The issue is that ``compute`` can not know if it is running in a script or in an interactive session. Typical HyperSpy usage involves an interactive session eventually followed by running a script once the code is refined. I think that the progress bar is useful in an interactive session. If it is an issue for a particular use case, it can always be disabled for a given method or, more generally, for all methods via the ``prefereces`` e.g.

```python
import hyperspy.api as hs
hs.preferences.General.show_progressbar = False
```
This will only affect the current session. For permanently disabling it for a given use:

```python
import hyperspy.api as hs
hs.preferences.General.show_progressbar = False
hs.preferences.save()
```
All of this is fine, however, you've identified a bug because ``LazySignal``'s ``compute`` doesn't honour the default set in ``preferences``, so I'm marking this as an easy to fix bug.

**Comment by uellue** [comment] 2018-02-21 10:00
@francisco-dlp At least on Unix you can easily get this information from `sys.stdout.isatty()` and `sys.stderr.isatty()` -- generally the `isatty()` method of a file object. 

Regarding stdout vs. stderr there are discussions, but it seems that stderr is better suited. https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout

Update: To be precise, it doesn't tell you if running interactively, but it DOES tell you if stdout is redirected to a file. Another indicator is this one: https://stackoverflow.com/questions/2356399/tell-if-python-is-in-interactive-mode

**Comment by magnunor** [comment] 2018-02-21 10:04
It is also possible to manually disable the progressbar when calling `s.compute` by using `progressbar=False`: `s.compute(progressbar=False)`.

HyperSpy uses `tqdm` for these progressbars, which should default to `sys.stderr`

**Comment by sk1p** [comment] 2018-02-21 10:14
`LazySignal` uses both `tqdm` and the dask implementation of a progress bar, `dask.diagnostics.progress.ProgressBar`, which writes to stdout:

https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/_signals/lazy.py#L87
https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/_signals/lazy.py#L434
https://github.com/dask/dask/blob/master/dask/diagnostics/progress.py#L30

So I guess the stdout -> stderr thing is a dask bug.

**Comment by francisco-dlp** [comment] 2018-02-21 10:20
Good catch @sk1p! It'll be good to report the inconsistency between ``dask``'s progress bar and ``tqdm``'s to the dask developers, are you planning to do that?

@uellue, how would you use the ``isatty`` method of a file object to help HyperSpy decide if to use a progress bar or not?

**Comment by sk1p** [comment] 2018-02-21 12:21
@francisco-dlp actually @uellue is currently preparing a pull request for that.

As for `isatty`: when piping `stderr` or `stdout` to a file or another command, `isatty()` returns `False` - in that case the progress bar doesn't make much sense anyway IMHO and can be disabled. This does not handle the case of just running a script non-interactively without redirecting stdout/stderr - I guess in that case it is up to the script author to decide if a progress bar makes sense.

**Comment by tjof2** [comment] 2020-09-03 09:30
Is this still an issue?

**Closed as completed** 2020-09-11 14:15 UTC
Labels: type: bug, good first PR
