### ISSUE TITLE
Scipy 0.17 issue in HyperSpy 1.2 Windows bundle installers 

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy#1548] opened 2017-03-22 17:00 UTC
It looks like the scipy version in the last HyperSpy 1.2 Windows bundle installers is not working properly on _some_ system. There is an error during the import of `scipy.linalg` - see error below.
We have tried to install the Visual C++ 2015 redistributable, but surprisingly it didn't help to solve the problem. 
Upgrading scipy to last version (0.19) solved the problem.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f1e39a18fd4e> in <module>()
      1 import matplotlib
      2 get_ipython().magic('matplotlib qt')
----> 3 import hyperspy.api as hs

C:\Program Files\HyperSpy WinPython Bundle v1.2\python-3.5.1.amd64\lib\site-packages\hyperspy\api.py in <module>()
     73 
     74 from hyperspy.Release import version as __version__
---> 75 from hyperspy import signals
     76 from hyperspy.io import load
     77 from hyperspy.defaults_parser import preferences

C:\Program Files\HyperSpy WinPython Bundle v1.2\python-3.5.1.amd64\lib\site-packages\hyperspy\signals.py in <module>()
     40 
     41 # -*- coding: utf-8 -*-
---> 42 from hyperspy.signal import BaseSignal
     43 from hyperspy._signals.lazy import LazySignal
     44 from hyperspy._signals.signal1d import (Signal1D, LazySignal1D)

C:\Program Files\HyperSpy WinPython Bundle v1.2\python-3.5.1.amd64\lib\site-packages\hyperspy\signal.py in <module>()
     34 from hyperspy import io
     35 from hyperspy.drawing import mpl_hie, mpl_hse, mpl_he
---> 36 from hyperspy.learn.mva import MVA, LearningResults
     37 import hyperspy.misc.utils
     38 from hyperspy.misc.utils import DictionaryTreeBrowser

C:\Program Files\HyperSpy WinPython Bundle v1.2\python-3.5.1.amd64\lib\site-packages\hyperspy\learn\mva.py in <module>()
     32 from hyperspy.misc.machine_learning import import_sklearn
     33 import hyperspy.misc.io.tools as io_tools
---> 34 from hyperspy.learn.svd_pca import svd_pca
     35 from hyperspy.learn.mlpca import mlpca
     36 from hyperspy.learn.rpca import rpca_godec, orpca

C:\Program Files\HyperSpy WinPython Bundle v1.2\python-3.5.1.amd64\lib\site-packages\hyperspy\learn\svd_pca.py in <module>()
     20 
     21 import numpy as np
---> 22 import scipy.linalg
     23 
     24 from hyperspy.misc.machine_learning.import_sklearn import (

C:\Program Files\HyperSpy WinPython Bundle v1.2\python-3.5.1.amd64\lib\site-packages\scipy\linalg\__init__.py in <module>()
    172 from .linalg_version import linalg_version as __version__
    173 
--> 174 from .misc import *
    175 from .basic import *
    176 from .decomp import *

C:\Program Files\HyperSpy WinPython Bundle v1.2\python-3.5.1.amd64\lib\site-packages\scipy\linalg\misc.py in <module>()
      3 import numpy as np
      4 from numpy.linalg import LinAlgError
----> 5 from .blas import get_blas_funcs
      6 from .lapack import get_lapack_funcs
      7 

C:\Program Files\HyperSpy WinPython Bundle v1.2\python-3.5.1.amd64\lib\site-packages\scipy\linalg\blas.py in <module>()
    153 import numpy as _np
    154 
--> 155 from scipy.linalg import _fblas
    156 try:
    157     from scipy.linalg import _cblas

ImportError: DLL load failed: The specified module could not be found.

**Comment by ericpre** [comment] 2017-03-22 17:05
Worth mentioning, that this issue does not need any fix, since last scipy version seems to work.
The aim of this issue is to provide a workaround in the mean time that a new HyperSpy Windows bundle installers is released.

**Comment by francisco-dlp** [comment] 2017-03-23 10:46
Have you tried after installing the MS Visual C++ package [from this link](https://www.microsoft.com/en-gb/download/details.aspx?id=48145)?

**Comment by rbjorge** [comment] 2017-03-29 10:02
Installing MSVC++ did not work for me (Windows 7). Installing scipy 0.19 did not work either ("No Lapack/Blas resources found"). I therefore installed the following wheels from http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy :
numpy-1.12.1+mkl-cp35-cp35m-win_amd64.whl
scipy-0.19.0-cp35-cp35m-win_amd64.whl
That solved the problem for me.

**Comment by ericpre** [comment] 2017-03-29 10:38
Sorry, I forgot to reply to this before, I wanted to test it on some more system. WE had the issue on windows 10 and windows 7.
@francisco-dlp, yes, we did first tried to install the redistribuable, but it did not solve the issue.
We used the exact same workaround as @rbjorge!

**Comment by francisco-dlp** [comment] 2017-03-29 10:42
Thanks for the feedback! It may be that it is [this version](https://www.microsoft.com/en-us/download/details.aspx?id=15336) that must be installed instead. I've tried to find it out, but I haven't been able to reproduce the issue myself after uninstalling all the libraries in my windows machine.

We'll be making a new release soon, could any of you test the new bundle once ready to make sure that the issue is gone?

**Comment by woozey** [comment] 2017-03-29 11:07
I've seen the same problem last week on a Windows 7 machine. Upgrading scipy and installing numpy+mkl worked as @rbjorge reported... I can try checking the installation @francisco-dlp  linked above on one of our shared Win7 machines today.

**Comment by ericpre** [comment] 2017-03-29 11:13
Actually, I have got a virtualbox where I can reproduce. Making a backup, before installing any redistribuable! ;)

**Comment by ericpre** [comment] 2017-03-30 20:53
I reproduced the bug: with HyperSpy bundle 1.1.2 and 1.2 installed on the same windows 7; importing `scipy.linalg` works in the first one, but not the second one. The SciPy version is the same in both bundles.
Installing MS Visual C++ redistribuable 2008 and 2015 did not help.

I finally install gohlke binaries in the 1.2 bundle to make sure this is reproducing the bug and it makes the import of scipy works...

**Comment by francisco-dlp** [comment] 2017-03-30 21:24
Thanks @ericpre! The fact that 1.1.2 works but not 1.2 probably means that upgrading some of the winpython packages [in this line](https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/appveyor.yml#L134) is introducing the issue.

**Comment by woozey** [comment] 2017-03-31 09:03
Short update: the same result on our Win7 machine with version 1.2.

**Comment by francisco-dlp** [comment] 2017-03-31 17:31
Fixed in #1562

**Closed as completed by francisco-dlp** 2017-03-31 17:31 UTC
Labels: type: bug

**Comment by thomasaarholt** [comment] 2017-05-05 14:03
This is now a month old - meaning, noone has been able to install hyperspy without knowledge of pip etc. on Windows since then.

Can we build a new windows binary and get it on the website?

**Comment by francisco-dlp** [comment] 2017-05-05 14:14
That's my fault: if you remember, I thought that we could release v1.3 instead of a patch release a couple of weeks ago to fix this among other issues. However, something urgent got on my way and v1.3 is yet to happen. From today, releasing v1.3 got back to the top of my priorities, so #1548 et al. should soon become history.
