### ISSUE TITLE
s.remove_background span sometimes not working

### ISSUE THREAD

**Issue by magnunor** [hyperspy/hyperspy#1065] opened 2016-06-07 14:14 UTC
During the Scandem workshop (using 0.8.5) some of the participants could not use the span selector to select a region when using s.remove_background().

I'm not really certain what trigged it, but several of the participants had the problem.

I'm guessing it has something to do with which of the GUI windows are selected first.

**Comment by francisco-dlp** [comment] 2016-06-07 17:00
I propose to label it "bug?" until someone finds a way to reproduce it.

**Comment by jat255** [comment] 2016-06-07 17:02
Is this related to the bug where the tool window disappears? I still see
that problem when I use that method interactively.

On Tue, Jun 7, 2016 at 1:00 PM, Francisco de la Peña <
notifications@github.com> wrote:

> I propose to label it "bug?" until someone finds a way to reproduce it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hyperspy/hyperspy/issues/1065#issuecomment-224345649>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABOBXYPkUQHrmuGJV2iQHK8Y6MWAU8c-ks5qJaOQgaJpZM4Iv-C5>
> .
>



-- 
Joshua Taillon
Materials Science and Engineering
University of Maryland, College Park
www.joshuataillon.com

**Comment by magnunor** [comment] 2016-06-07 19:05
@francisco-dlp, agreed.

@jat255, I don't think so. Since the box was still present. 

It was really odd though, since running through exactly the same steps did not replicate it...

**Comment by thomasaarholt** [comment] 2016-06-08 13:46
Yes. On my mac if I just click, instead of dragging, the span selection across signals stops working. I need to click and drag for it to work. The same applies in spikes_removal_tool.

**Comment by thomasaarholt** [comment] 2016-10-21 10:14
This is still a big issue for me. Does this affect windows/linux users? I get this 90% of the time when I run `s.remove_background()` and have to rerun that code by itself and try again and again until it randomly holds.

**Comment by ericpre** [comment] 2019-06-19 15:47
Closing this because the span selector have been improved quite a bit over the last few releases.

**Closed by ericpre** 2019-06-19 15:47 UTC
Labels: release: next patch, type: bug?
