### ISSUE TITLE
Refreshing plots bug

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#1096] opened 2016-06-20 19:13 UTC
The following is probably entirely to do with me using matplotlib v2 (from github master), but I assume we'll eventually be using it, so here goes:

_Sometimes_, and I haven't entirely figured it out yet - but it's most of the time, stepping through the navigation dimension in a plot yields the following change on the plot:

Before stepping:
<img width="912" alt="screenshot 2016-06-20 20 15 21" src="https://cloud.githubusercontent.com/assets/2721423/16207194/bfdf4844-3723-11e6-9008-7a20599495e5.png">

After stepping:
<img width="912" alt="screenshot 2016-06-20 20 08 59" src="https://cloud.githubusercontent.com/assets/2721423/16207085/4e541d6c-3723-11e6-935f-12c9ae9f3f62.png">

~~The actual signal does not get "fat".~~ I'm a big fat liar. Everything gets overlaid.

How "optimized" is `.plot()`? Does it refresh the axis on every step through `.nav`? Does it need to? (I assume the problem here is that it keeps overlaying rather than updating.

Alt + Tab-ing out and in fixes it.

**Comment by francisco-dlp** [comment] 2016-07-13 14:28
I couldn't reproduce it with mpl 2 beta1. It looks like a blit issue.

**Comment by dnjohnstone** [comment] 2016-07-25 09:46
I wonder if this is a mac related issue although not sure why that should be. I think I saw something similar from someone the other day (also on a mac), but I was only half concentrating with a HyperSpy hat on.

**Comment by thomasaarholt** [comment] 2016-08-08 21:13
Just pointing out that it is still an issue with the latest master matplotlib v2. It probably slows down my interactive ROI by quite a bit. Not a huge issue, but a bit strange that it seems only prevalent on Mac.

**Comment by thomasaarholt** [comment] 2016-11-20 12:51
This bug is also present on my colleague's windows install. Has anyone else noticed this?

**Comment by thomasaarholt** [comment] 2016-11-20 12:51
His was a conda windows install, for reference.

**Comment by ericpre** [comment] 2019-06-03 19:25
Closing because I think this is not relevant anymore: matplotlib is now at 3.* and the situation with plotting have been improved significantly since #1890,  #1904 and #2024 (and also from the matplotlib side).

**Closed by ericpre** 2019-06-03 19:25 UTC
Labels: release: next patch, type: bug?
