### ISSUE TITLE
invalid 'pyqt5' in  pyqt=4 Anaconda environment

### ISSUE THREAD

**Issue by hentr** [hyperspy/hyperspy#1616] opened 2017-05-05 14:15 UTC
Hey, I had hyperspy running in an Anaconda environment, but after rebooting my computer,  trying to  import hyperspy.api gives 'RuntimeError: Invalid Qt API 'pyqt5', valid values are: 'pyqt' or 'pyside' ' 

Using freshly reinstalled Anaconda, installed hyperspy (tried 1.0, 1.1, 1.2) in python 3.6 or 3.5 environments as per #1499,  and `conda install pyqt=4`

Have tried a couple of reinstalls of Anaconda, a few new environments, running from python terminal or jupyther notebook, always the same. 
Any idea?
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-ebbc5c8c5cbc> in <module>()
      7 
      8 # Import the HyperSpy wrapper for PGURE-SVT
----> 9 from pguresvt import hspysvt
     10 from pguresvt.pguresvt import PoissonGaussianNoiseGenerator

C:\Users\hent\polybox\QSTEM matlab\PGURE-SVT_Win64\pguresvt\hspysvt.py in <module>()
----> 1 from hyperspy import signals
      2 
      3 try:
      4     from pguresvt.pguresvt import SVT
      5 except ImportError:

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\hyperspy\signals.py in <module>()
     40 
     41 # -*- coding: utf-8 -*-
---> 42 from hyperspy.signal import BaseSignal
     43 from hyperspy._signals.lazy import LazySignal
     44 from hyperspy._signals.signal1d import (Signal1D, LazySignal1D)

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\hyperspy\signal.py in <module>()
     33 from hyperspy.axes import AxesManager
     34 from hyperspy import io
---> 35 from hyperspy.drawing import mpl_hie, mpl_hse, mpl_he
     36 from hyperspy.learn.mva import MVA, LearningResults
     37 import hyperspy.misc.utils

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\hyperspy\drawing\mpl_hie.py in <module>()
     17 # along with  HyperSpy.  If not, see <http://www.gnu.org/licenses/>.
     18 
---> 19 from hyperspy.drawing import image, utils
     20 from hyperspy.drawing.mpl_he import MPL_HyperExplorer
     21 

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\hyperspy\drawing\image.py in <module>()
     25 from hyperspy.drawing import widgets
     26 from hyperspy.drawing import utils
---> 27 from hyperspy.gui.tools import ImageContrastEditor
     28 from hyperspy.misc import math_tools
     29 from hyperspy.misc import rgb_tools

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\hyperspy\gui\tools.py in <module>()
     23 import matplotlib.pyplot as plt
     24 import traits.api as t
---> 25 import traitsui.api as tu
     26 from traitsui.menu import (OKButton, CancelButton, OKCancelButtons)
     27 

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\traitsui\api.py in <module>()
     34 
     35 try:
---> 36     from .editors.api import ArrayEditor
     37 except ImportError:
     38     # ArrayEditor depends on numpy, so ignore if numpy is not present.

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\traitsui\editors\__init__.py in <module>()
     21 
     22 try:
---> 23     from .api import ArrayEditor
     24 except ImportError:
     25     pass

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\traitsui\editors\api.py in <module>()
     22 from .button_editor import ButtonEditor
     23 from .check_list_editor import CheckListEditor
---> 24 from .code_editor import CodeEditor
     25 from .color_editor import ColorEditor
     26 from .compound_editor import CompoundEditor

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\traitsui\editors\code_editor.py in <module>()
     34 #-------------------------------------------------------------------------------
     35 
---> 36 class ToolkitEditorFactory ( EditorFactory ):
     37     """ Editor factory for code editors.
     38     """

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\traitsui\editors\code_editor.py in ToolkitEditorFactory()
     46 
     47     # Background color for marking lines
---> 48     mark_color = Color( 0xECE9D8 )
     49 
     50     # Object trait containing the currently selected line (optional)

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\traits\traits.py in __call__(self, *args, **metadata)
    520 
    521     def __call__ ( self, *args, **metadata ):
--> 522         return self.maker_function( *args, **metadata )
    523 
    524 class TraitImportError ( TraitFactory ):

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\traits\traits.py in Color(*args, **metadata)
   1234     from traitsui.toolkit_traits import ColorTrait
   1235 
-> 1236     return ColorTrait( *args, **metadata )
   1237 
   1238 Color = TraitFactory( Color )

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\traitsui\toolkit_traits.py in ColorTrait(*args, **traits)
      5 
      6 def ColorTrait ( *args, **traits ):
----> 7     return toolkit().color_trait( *args, **traits )
      8 
      9 def RGBColorTrait ( *args, **traits ):

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\traitsui\toolkit.py in toolkit(*toolkits)
    150     if ETSConfig.toolkit:
    151         # If a toolkit has already been set for ETSConfig, then use it:
--> 152         _toolkit = _import_toolkit(ETSConfig.toolkit)
    153         return _toolkit
    154     else:

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\traitsui\toolkit.py in _import_toolkit(name)
     81 
     82 def _import_toolkit ( name ):
---> 83     return __import__( name, globals=globals(), level=1 ).toolkit
     84 
     85 

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\traitsui\qt4\__init__.py in <module>()
     16 # import pyface.qt before anything else is done so the sipapi
     17 # can be set correctly if needed
---> 18 import pyface.qt
     19 
     20 #----------------------------------------------------------------------------

C:\Users\hent\AppData\Local\Continuum\Anaconda3\envs\testenv2\lib\site-packages\pyface\qt\__init__.py in <module>()
     42 elif qt_api != 'pyside':
     43     raise RuntimeError("Invalid Qt API %r, valid values are: 'pyqt' or 'pyside'"
---> 44                        % qt_api)

RuntimeError: Invalid Qt API 'pyqt5', valid values are: 'pyqt' or 'pyside'
```

**Comment by francisco-dlp** [comment] 2017-05-05 14:18
The error suggests that you environment still has qt5 installed intead of qt4.

What do you get when running the following?:

```bash

conda install pyqt=4.11.4

```

**Comment by hentr** [comment] 2017-05-05 14:30
I get 
```
#All requested packages already installed. 
#packages in environment at C:\Usershent\AppData\Local\Continuum\Anaconda3\testenv2: 
#pyqt            4.11.4           py36_2        conda-forge
```

**Comment by francisco-dlp** [comment] 2017-05-05 14:31
Are you initiating the qt4 backend explicitly i.e. ``%matplotlib qt4``?

**Comment by hentr** [comment] 2017-05-05 14:34
that worked! thanks

**Comment by hentr** [comment] 2017-05-05 16:21
Was a bit too quick there. Commenting out `%matplotlib`, I can import hyperspy, but with `%matplotlib`, `%matplotlib qt` or `%matplotlib qt4`, the same error as before

**Comment by francisco-dlp** [comment] 2017-05-05 16:23
Are you running the matplotlib magic before any other command after restarting the kernel? 

```python

%matplotlib qt4
import hyperspy.api as hs

```

**Comment by hentr** [comment] 2017-05-05 16:39
yup, 1st line of first (code) cell

**Comment by francisco-dlp** [comment] 2017-05-05 16:42
That's puzzling. The only solution that I can offer you without being able to reproduce the issue is to install this development branch:

```bash

pip install --upgrade https://github.com/francisco-dlp/hyperspy/archive/ipywidgets.zip

```

There this and many other issues should be fixed, and you can even use ipywidgets and the nbagg backend if you like, see #1544  for details.

**Comment by jeinsle** [comment] 2017-05-06 07:47
I have been getting this on several of the machine while I have been installing or upgrading Hyperspy  recently.  Had to explicitly downgrade pyqt to 4.xxx

**Comment by thomasaarholt** [comment] 2017-05-06 12:17
@hentr, just to be super-clear: Could you start a new instance of the notebook, and then do paste the following?

```python
%matplotlib qt4
import hyperspy.api as hs
hs.datasets.example_signals.EDS_SEM_Spectrum().plot()
```

**Comment by hentr** [comment] 2017-05-08 17:39
@thomasaarholt gives the same error as before.

@francisco-dlp, I get hyperspy running with ipywidgets, thanks!

**Closed as completed** 2017-05-09 15:37 UTC

**Comment by WolfgangKoe** [comment] 2017-06-26 10:31
Hey guys,

sorry for starting the discussion again. I just installed hyperspy in an anaconda environment. 

```
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
```
.

Entering `%matplotlib` gives:

`Using matplotlib backend: Qt5Agg`

Entering  `import hyperspy.api as hs` gives:

`RuntimeError: Invalid Qt API 'pyqt5', valid values are: 'pyqt' or 'pyside'`

as mentioned before by many people.

.

Trying `%matplotlib qt` or `%matplotlib qt` gives:

`ModuleNotFoundError: No module named 'PyQt4'`

what looks like the same problem as mentioned here, that I need to install the version pyqt4 with:

`conda install pyqt=4` or `conda install pyqt=4.11.4`

But in both cases I get:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - pyqt 4.11.4* -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

Am I doing something wrong (what is not unlikely, since I just started working with Linux) or is there something else?

greetings

**Comment by francisco-dlp** [comment] 2017-06-26 10:39
Could you try again after updating pyface and traitsui as follows?

```bash

pip install https://github.com/enthought/pyface/archive/master.zip
pip install https://github.com/enthought/traitsui/archive/master.zip
```

**Comment by WolfgangKoe** [comment] 2017-06-26 11:03
This was the problem I guess. I tested it with some data and it worked. 

Thanks a lot.

**Comment by JochenKa** [comment] 2017-07-03 09:46
Hello, apparently I have the same problem as Wolfgang: I cannot install pyqt 4 and generate the exact same error message: 

```
UnsatisfiableError: The following specifications were found to be in conflict:
- pyqt 4.11.4* -> python 2.7* -> openssl 1.0.1*
- python 3.6*
```

Somehow, francisco's solution does not work for me. Any other suggestions?

Best,
Jochen

**Comment by thomasaarholt** [comment] 2017-07-03 09:55
The easiest temporary fix for you is just to use the built-in notebook backend (use `%matplotlib nbagg` instead of `%matplotlib qt4`). It has pros and cons (inline, but slower). On windows you can also use `%matplotlib tk`

What about @francisco-dlp's solution did not work?

**Comment by JochenKa** [comment] 2017-07-03 10:09
Using `%matplotlib nbagg` does not work either: `ModuleNotFoundError: No module named 'PyQt4'`

About @francisco-dlp's solution: Both installations run successfully but the Error during the installation of "pyqt 4" remains

**Comment by thomasaarholt** [comment] 2017-07-03 14:45
Restart jupyter and try again. You can just restart the kernel from the "Kernel" menu.

**Comment by thomasaarholt** [comment] 2017-07-03 14:45
What system are you running on? Windows, Mac, Linux?

**Comment by JochenKa** [comment] 2017-07-03 16:32
Ah, I see. Could have thought of that... Thanks a lot for your help! I'm running it on Linux. 

Is it possible to get it running in the terminal as well? NbAgg only works in the notebook, right? Running it in the terminal results in `UnknownBackend: No event loop integration for 'nbagg'. Supported event loops are: qt, qt4, qt5, gtk, gtk2, gtk3, tk, wx, pyglet, glut, osx`

**Comment by thomasaarholt** [comment] 2017-07-03 18:20
Qt really should work :/ the notebook won't work in the terminal. you mean the qtconsole right?

Are you sure you are writing "%matplotlib qt5" and not just "%matplotlib"?

**Comment by JochenKa** [comment] 2017-07-04 16:43
I didn't make myself clear. I'm sorry! What I'm trying to is to get the traitsui GUI for hyperspy in the qtconsole running. I can indeed run qt5 but need qt4 for traitsui and cannot install it. `conda install pyqt=4.11.4 -y` yields 
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - pyqt 4.11.4* -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```
This is the same problem, as @WolfgangKoe had, but the fix by # @francisco-dlp did somehow not work for me. 
Thanks to you, @thomasaarholt, I can now run the ipywidgets GUI in jupyter with the NbAgg backend but I would also like to use traitsui. 

...Or do I miss something here? These are my first experiences with hyperspy.

**Comment by francisco-dlp** [comment] 2017-07-04 16:50
You could upgrade traitsui and pyface to their dev versions as explained above:

```bash

pip install https://github.com/enthought/pyface/archive/master.zip
pip install https://github.com/enthought/traitsui/archive/master.zip
```

Then you should be able to use traitsui from the qtconsole. You could test it with the following script:

```python

%matplotlib qt5
import hyperspy.api as hs
hs.preferences.gui()

```

**Comment by thomasaarholt** [comment] 2017-07-04 16:58
@JochenKa Can you confirm - do you need pyqt4 for any other reason than hyperspy? If not, go with qt5 as francisco suggests.

**Comment by JochenKa** [comment] 2017-07-05 07:49
@thomasaarholt No, I don't need pyqt4 for any other reason, I was just focused on it because of the [Getting Startded](http://hyperspy.org/hyperspy-doc/current/user_guide/getting_started.html) of Hyperspy.

@francisco-dlp It still doesn't work: 
```
In [1]: %matplotlib qt5

In [2]: import hyperspy.api as hs
WARNING:hyperspy.api:The traitsui GUI elements are not available, probably because the hyperspy_gui_traitui package is not installed.

In [3]: hs.preferences.gui()
<ipywidgets.widgets.widget_box.VBox at 0x7fb651177710>
```
I copied the results of the intallations to the attached txt file:
[installation_pip_log.txt](https://github.com/hyperspy/hyperspy/files/1123857/installation_pip_log.txt)

**Comment by francisco-dlp** [comment] 2017-07-05 09:19
Can you post the output of importing hyperspy_gui_traitsui after restarting the kernell?:

```python

%matplotlib qt5
import hyperspy_gui_traitsui

```

**Comment by JochenKa** [comment] 2017-07-05 09:43
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-2b3348f7a0f1> in <module>()
      1 get_ipython().magic('matplotlib qt5')
----> 2 import hyperspy_gui_traitsui

ModuleNotFoundError: No module named 'hyperspy_gui_traitsui'
```

**Comment by francisco-dlp** [comment] 2017-07-05 11:35
It looks like hyperspy_gui_traitsui is not installed in the Python environment where you are running your session. Could you try starting ipython in the terminal as follows and importing hyperspy_gui_traitsui there?

```bash

/home/jochenka/anaconda3/bin/ipython

```

**Comment by JochenKa** [comment] 2017-07-05 13:45
Hmm, doesn't work either. The output is the same.

**Comment by thomasaarholt** [comment] 2017-07-05 13:46
Okay, just install the gui:
`pip install hyperspy_gui_traitsui`

**Comment by francisco-dlp** [comment] 2017-07-05 13:48
Just to be sure that you're using the right pip, could you install it like this?

```bash
/home/jochenka/anaconda3/bin/pip install https://github.com/enthought/pyface/archive/master.zip
/home/jochenka/anaconda3/bin/pip install https://github.com/enthought/traitsui/archive/master.zip
/home/jochenka/anaconda3/bin/pip install hyperspy_gui_traitsui

```

**Comment by JochenKa** [comment] 2017-07-05 15:22
Ok, this is strange: I can import traitsui now but it's still not available as GUI and I cant use any of its functions:
```
In [1]: %matplotlib qt5
   ...: import hyperspy_gui_traitsui
   ...: import hyperspy.api as hs
   ...: hs.preferences.gui()
   ...: 
<ipywidgets.widgets.widget_box.VBox at 0x7efbea7c67b8>
```
```
In [2]: hs.load()
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-2-dea9113c7915> in <module>()
----> 1 hs.load()

/home/jochenka/anaconda3/lib/python3.6/site-packages/hyperspy/io.py in load(filenames, signal_type, stack, stack_axis, new_axis_name, lazy, **kwds)
    166         from hyperspy.signal_tools import Load
    167         load_ui = Load()
--> 168         get_gui(load_ui, toolkey="load")
    169         if load_ui.filename:
    170             filenames = load_ui.filename

/home/jochenka/anaconda3/lib/python3.6/site-packages/hyperspy/ui_registry.py in get_gui(self, toolkey, display, toolkit, **kwargs)
    164                 _toolkits_to_string(toolkits),
    165                 is_or_are,
--> 166                 _toolkits_to_string(available_toolkits)))
    167     if not display:
    168         return widgets

NotImplementedError: The ipywidgets toolkit is not available for this functionality,try with the traitsui toolkit.
```

**Comment by francisco-dlp** [comment] 2017-07-05 15:25
Can you try without importing hyperspy_gui_traitsui explicitly?

```python

%matplotlib qt5
import hyperspy.api as hs
hs.preferences.gui()

```

**Comment by JochenKa** [comment] 2017-07-05 15:28
Sure! Same result

**Comment by francisco-dlp** [comment] 2017-07-05 15:29
Do you get any error?

**Comment by JochenKa** [comment] 2017-07-05 15:30
No, just `<ipywidgets.widgets.widget_box.VBox at 0x7f75919d1b38>` again

**Comment by francisco-dlp** [comment] 2017-07-05 15:32
What do you get with the following?:

```
%matplotlib qt5
import hyperspy.api as hs
hs.preferences.gui(toolkit="traitsui")
```

**Comment by JochenKa** [comment] 2017-07-05 15:37
The Preferences appear :

![grafik](https://user-images.githubusercontent.com/29857227/27872238-6a0b381e-61a8-11e7-88db-cc8c1472313b.png)

Edit: And I can use the traitsui functions now after enabling the traitsui GUI . Thank you very much!!
