### ISSUE TITLE
Interactive plotting is broken when using the widget (ipympl) backend in jupyter lab/notebook with matplotlib>=3.4

### ISSUE THREAD

**Issue by francisco-dlp** [hyperspy/hyperspy#2706] opened 2021-04-13 14:32 UTC
Here is an illustration of the issue when using the ``ipympl`` backend
![no_blit_bug](https://user-images.githubusercontent.com/989719/114570056-ca0eb400-9c75-11eb-81a0-2bbac2e5bc2d.png)

**Comment by francisco-dlp** [comment] 2021-04-13 14:39
The issue is present also with hyperspy v1.6.1 when using matplotlib 3.4.1. Therefore, it is an issue of compatibility with matplotlib >=3.4 or a matplotlib bug. I'll amend the title accordingly.

**Comment by ericpre** [comment] 2021-04-13 14:41
I suspect this is with the widget backend and that the notebook backend works fine! Can you check?

The following runs fine in the notebook:

```python
%matplotlib notebook
import hyperspy.api as hs
import numpy as np

s = hs.datasets.artificial_data.get_core_loss_eels_line_scan_signal(True)
s.plot()
```

![image](https://user-images.githubusercontent.com/11851990/114571605-b744b100-9c6e-11eb-8840-b02ac8751f81.png)

**Comment by ericpre** [comment] 2021-04-13 14:44
The same with the widget backend in the jupyterlab:

![image](https://user-images.githubusercontent.com/11851990/114572027-0985d200-9c6f-11eb-8a60-6840bb346ed8.png)

**Comment by francisco-dlp** [comment] 2021-04-13 14:51
That sounds like an ``ipympl`` compatibility issue with matplotlib>=3.4 then.

**Comment by ericpre** [comment] 2021-04-13 15:08
This doesn't seem to work for any of the combination between matplotlib 3.3.4/3.4.1 and ipympl 0.6/0.7.

**Comment by thomasaarholt** [comment] 2021-04-13 21:00
I agree that it's a ipympl issue. The following rectangle example also doesn't work with ipympl. I know there was some chat about supporting blitting recently, but the following example has `useblit=False`, so maybe its something else. Looks like something isn't right:

```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.widgets  import RectangleSelector

xdata = np.linspace(0,9*np.pi, num=301)
ydata = np.sin(xdata)

fig, ax = plt.subplots()
line, = ax.plot(xdata, ydata)


def line_select_callback(eclick, erelease):
    x1, y1 = eclick.xdata, eclick.ydata
    x2, y2 = erelease.xdata, erelease.ydata

    rect = plt.Rectangle( (min(x1,x2),min(y1,y2)), np.abs(x1-x2), np.abs(y1-y2) )
    ax.add_patch(rect)


rs = RectangleSelector(ax, line_select_callback,
                       drawtype='box', useblit=False, button=[1], 
                       minspanx=5, minspany=5, spancoords='pixels', 
                       interactive=True)

# plt.show()
```
![image](https://user-images.githubusercontent.com/2721423/114620657-1674e680-9cac-11eb-8333-ab848c989567.png)

**Comment by francisco-dlp** [comment] 2021-04-14 09:41
On further testing, the issue is not that reproducible. I can reproduce it in my laptop (but with varying severity) but not in my desktop computer. I cannot reproduce it using a Kaggle notebook either using ipympl. Therefore, it may have something to do with jupyter rather than ipympl after all.

@thomasaarholt, I think that you've found a but in matplotlib's ``RectangleSelector`` that is unrelated to this issue: you get the same wrong behaviour using the qt backend.

**Comment by ericpre** [comment] 2021-04-14 10:39
It looks to me that there is nothing we can do here, expect trying to narrow down the issue and report it to https://github.com/matplotlib/ipympl.

One thing that I have noticed is that resizing the figure, correct the incorrect drawing and this may point out toward a blitting issue, because resize of the figure usually trigger a full redraw. I wasn't expected this because my understanding was that ipympl doesn't use blitting, but this may be wrong!

**Comment by ericpre** [comment] 2021-04-14 10:50
> On further testing, the issue is not that reproducible. I can reproduce it in my laptop (but with varying severity) but not in my desktop computer. I cannot reproduce it using a Kaggle notebook either using ipympl. Therefore, it may have something to do with jupyter rather than ipympl after all.

Indeed, this is working well in the jupyter notebook but in not the jupyter lab (both with the **widget** backend)! Maybe it may be good putting of the list of packages on kaggle, to try to reproduce a working environment from a non working one...

**Comment by thomasaarholt** [comment] 2021-04-15 19:58
> @thomasaarholt, I think that you've found a but in matplotlib's `RectangleSelector` that is unrelated to this issue: you get the same wrong behaviour using the qt backend.

I don't have any issues with it not working - it works fine here. Perhaps try [this example](https://matplotlib.org/stable/gallery/widgets/rectangle_selector.html#sphx-glr-gallery-widgets-rectangle-selector-py) instead just to compare? It has slightly different behaviour.

**Comment by francisco-dlp** [comment] 2021-04-16 06:57
The first example  works for me with ``qt`` and ``useblit=True``, but with ``useblit=False`` I get the same behaviour that you reported above. The second works for me regardless of the value of ``useblit``.

**Comment by ericpre** [comment] 2022-08-22 18:11
Closing as I can't reproduce with more recent versions of dependencies. There have been a lot of changes in ipympl and this is very likely that this has been fixed there.

**Closed as completed by ericpre** 2022-08-22 18:11 UTC
Labels: type: external bug

**Comment by thomasaarholt** [comment] 2022-08-22 18:49
I actually see quite a bit of tearing in jupyter lab on Mac OS, but not in jupyter notebook. I'll provide an example tomorrow, but I saw this with a spanroi last week.
