### ISSUE TITLE
Improve reading/writing speed of hspy files

### ISSUE THREAD

**Issue by blazzter** [hyperspy/hyperspy#1739] opened 2017-09-27 04:57 UTC
Is there a way how to make hdf5 faster to read/write? If I convert my data (>2GB) to h5py, it just takes much much longer to load it compared to simple binary read.

**Comment by robindegen** [comment] 2017-09-27 05:07
I've noticed it really depends on how you write it. For example if your dataset is expandable it's slower than if it's assigned it's required size up front. Also the chunk size matters greatly in terms of peformance.

**Comment by magnunor** [comment] 2017-09-27 08:43
I've seen the same thing myself, with binary files loading much faster compared to HDF5-files.

One trick is using `s = hs.load("afile.hdf5", lazy=True)`, which means the data is not loaded into memory, unless you need it to be. See http://hyperspy.org/hyperspy-doc/current/user_guide/big_data.html#working-with-big-data for more info.

I've especially found the plotting example to be very useful:
```python
# for fastest results, just pick one signal space pixel
nav = s.isig[256, 256].T
# Alternatively, sum as per default behaviour
nav = s.sum(s.axes_manager.signal_axes).T
nav.compute()

s.plot(navigator=nav)
```

**Comment by ericpre** [comment] 2017-09-27 10:37
Yes, there may be room for improvement of reading/writing speed of hspy files; it needs to be checked. I rename the title of the issue to more it more clear.

**Comment by magnunor** [comment] 2017-09-27 10:56
Making things read faster might be difficult, since our read speed is limited by how `h5py` does it. The fact that binary files or the same data saved as a flat NumPy files loads faster, might be due to various overheads in the `h5py` file-reader. This _might_ be improved by making it run in parallel mode (http://docs.h5py.org/en/latest/mpi.html), but I haven't tried this.

Another important factor is how we save the data, as mentioned by @robindegen the chunking size and other settings can have very large effects on the time it takes to load the data. So we might be able to improve the loading time of data saved in HyperSpy, by changing some of these settings.

**Comment by ericpre** [comment] 2017-09-27 11:36
On example of a pitfall: for #1662, if I remember correctly, I had massive improvement in reading speed with a simple change in the way the data are accessed, possibly the change in [this line](https://github.com/hyperspy/hyperspy/pull/1662/commits/45176631be8c7d48542aed97504bfdfa1d6874a6#diff-9a9e452522a6c34ae2dd3782a26581d2R822): `self.spectrum_stream_group[name][:, 0]` versus `self.spectrum_stream_group['{}/Data'.format(key)][:].T[0]` and in particular `[:].T[0]` seemed to be faster than `[:, 0]`. In this particular case, the speed issue came from the way we the different libraries!

**Comment by ericpre** [comment] 2018-04-28 11:05
@blazzter, in #1934 I have checked the performance of writing/reading 1Go in hspy format (through h5py) and the performance is closed to binary file. Considering that inappropriate chunking may affect considerably the performance, could you please either provide a minimum example or a file reproducing the issue that you mentioned here?

**Comment by ericpre** [comment] 2018-08-03 17:55
@blazzter: by default, hyperspy use compression when writing hspy file and it does slow down significantly reading and writing.

**Comment by ericpre** [comment] 2021-01-27 18:43
Closing: if there is a performance issue, this is most likely because compression is being used or the chunking is not appropriate. In case of the latter, this should be a hdf5 issue.

**Closed as completed by ericpre** 2021-01-27 18:43 UTC
Labels: type: enhancement
