### ISSUE TITLE
Issue with RectangularROI when at least one image axis is negatively valued

### ISSUE THREAD

**Issue by MouloudHS** [hyperspy/hyperspy#2672] opened 2021-03-12 15:38 UTC
### Bug
When creating a RectangularROI on an image with at least one negatively valued axis, we lose control over the rectangular box in the direction of the negatively valued axis.

**Comment by thomasaarholt** [comment] 2021-03-12 15:57
Yes, I've noticed this behaviour too! Do you have a reproducible example for us?

**Comment by ericpre** [comment] 2021-03-12 16:28
https://github.com/hyperspy/hyperspy/issues/887

**Comment by thomasaarholt** [comment] 2021-03-12 16:29
Not bad remembering a 5 year old issue, @ericpre  :)

**Comment by ericpre** [comment] 2021-03-12 16:32
I referenced it 5 days ago, I have looked at some ROIs improvement in the last few months.

**Comment by ericpre** [comment] 2021-03-12 16:46
Example to reproduce with `SpanROI` to start simple and avoid the confusion mentioned in #2340...
```python
import numpy as np
import hyperspy.api as hs

negative_scale = True
s = hs.signals.Signal2D(np.random.rand(10, 4, 4))

if negative_scale:
    s.axes_manager[0].name = "negative"
    s.axes_manager[0].scale *= -1
    left, right = -5, -2
else:
    left, right = 2, 5
r = hs.roi.SpanROI(left, right)
s.plot()
r_sum = r.interactive(s)
```

**Comment by francisco-dlp** [comment] 2021-03-12 17:27
As pointed out by @ericpre, this is a duplicate of #887, so closing.

@ericpre, maybe you could post your code to reproduce the bug in #887?

**Closed as completed by francisco-dlp** 2021-03-12 17:27 UTC
