### ISSUE TITLE
read spectrum

### ISSUE THREAD

**Issue by woodg07** [hyperspy/hyperspy#2489] opened 2020-08-20 19:39 UTC
I'm trying to read in an spc spectrum but get the error below. I'm using the following versions let me know if you need more info:

mac osx 10.13.6
python 3.6.1
hyperspy==1.6.0
hyperspy-gui-ipywidgets==1.3.0
hyperspy-gui-traitsui==1.3.0
numba==0.49.0
numpy==1.18.5

Traceback (most recent call last):
  File "spc2csv2.py", line 9, in <module>
    hs.load('file.spc')
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io.py", line 341, in load
    for filename in filenames]
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io.py", line 341, in <listcomp>
    for filename in filenames]
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io.py", line 383, in load_single_file
    return load_with_reader(filename=filename, reader=reader, **kwds)
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io.py", line 390, in load_with_reader
    **kwds)
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io_plugins/edax.py", line 1019, in file_reader
    **kwargs)
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io_plugins/edax.py", line 781, in spc_reader
    dtype='u4', shape=(1, nz), **kwargs).squeeze()
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/numpy/core/memmap.py", line 247, in __new__
    bytes = long(offset + size*_dbytes)
TypeError: only size-1 arrays can be converted to Python scalars

**Comment by woodg07** [comment] 2020-08-20 19:39
....and this is the contents of the script:

import hyperspy.api as hs
import hyperspy.io
import csv
import numpy as np
import os
hs.preferences.GUIs.warn_if_guis_are_missing = False
hs.preferences.save()
hs.load('file.spc')

**Comment by ericpre** [comment] 2020-08-21 12:35
Can you share a file to reproduce the issue?

**Comment by jat255** [comment] 2020-08-21 13:39
> Can you share a file to reproduce the issue?

Yes, please share if you can. Or any additional details you have about the file. There are many types of files that are saved with the `.spc` extension. We only support single EDS spectrum files saved by the EDAX TEAM/Genesis software. If this is a Thermo Raman/FTIR/etc. file, we do not support that natively.

**Comment by woodg07** [comment] 2020-08-21 13:42
looks like the second comment answered my question...this was on a Thermo Raman...my response below
[file.spa.txt](https://github.com/hyperspy/hyperspy/files/5109111/file.spa.txt)
[file.spc.txt](https://github.com/hyperspy/hyperspy/files/5109112/file.spc.txt)



Unfortunately the one I tested it on is proprietary data so I cannot share.  I did take a scan of another compound and I'm attaching those scans here. It was done on a different instrument and the errors I get are slightly different. For the spc file I get:

  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io.py", line 341, in load
    for filename in filenames]
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io.py", line 341, in <listcomp>
    for filename in filenames]
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io.py", line 383, in load_single_file
    return load_with_reader(filename=filename, reader=reader, **kwds)
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io.py", line 390, in load_with_reader
    **kwds)
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io_plugins/edax.py", line 1019, in file_reader
    **kwargs)
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io_plugins/edax.py", line 781, in spc_reader
    dtype='u4', shape=(1, nz), **kwargs).squeeze()
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
OverflowError: memory mapped length must be positive


and for the spa file I get:

  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io.py", line 341, in load
    for filename in filenames]
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io.py", line 341, in <listcomp>
    for filename in filenames]
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io.py", line 383, in load_single_file
    return load_with_reader(filename=filename, reader=reader, **kwds)
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io.py", line 390, in load_with_reader
    **kwds)
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/hyperspy/io_plugins/mrcz.py", line 79, in file_reader
    **kwds)
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/mrcz/ioMRC.py", line 279, in readMRC
    header, slices = readMRCHeader(MRCfilename, slices, endian=endian, fileConvention = fileConvention, pixelunits=pixelunits)
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/mrcz/ioMRC.py", line 488, in readMRCHeader
    mrcz_version = _getMRCZVersion(f.read(80))
  File "/Users/woodg07/anaconda3/envs/impy/lib/python3.6/site-packages/mrcz/ioMRC.py", line 202, in _getMRCZVersion
    label = label.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 66: invalid continuation byte

**Comment by jat255** [comment] 2020-08-21 14:12
Thanks for the details. As I mentioned, our .spc reader is only for one specific type of spc file, so your files unfortunately cannot be imported natively into HyperSpy. You would be able to use HyperSpy if you can get the data into a NumPy array, and then you could build the signal from that to use HyperSpy's processing tools.

Depending on you appetite, you could pull the data out of the binary directly using the tips from [this](https://github.com/wojdyr/xylib/issues/11) page. Alternatively, it appears there is a Python reader for this format here: https://github.com/rohanisaac/spc (I have not tested it, but it seems like the right thing). If you would like to contribute a reader for this format to HyperSpy, we'd love to have the contribution, in which case you can follow the [Developer Guide](http://hyperspy.org/hyperspy-doc/current/dev_guide/index.html) for more details on how to get started.

**Comment by jat255** [comment] 2020-08-21 14:13
I'm going to go ahead and close this issue for the time being, since this isn't a format we support.

**Closed as completed by jat255** 2020-08-21 14:13 UTC

**Comment by ericpre** [comment] 2020-08-21 15:38
Thanks @jat255 for the clarification, I have open an issue to keep track of the information.
