### ISSUE TITLE
Antivirus blocks 64-bit bundle installer

### ISSUE THREAD

**Issue by matthcarpenter** [hyperspy/hyperspy#1664] opened 2017-06-02 15:33 UTC
I am using Symantec antivirus on Windows 10.  When I try to download the installer for the 64-bit Hypermap bundle, it is flagged and removed by my antivirus before the download completes.  

It lists the threat name as  SAPE.Heur.ba757 .

I can post the contents of the threat warming separately if needed, but I will need to redact some personal info.

**Comment by francisco-dlp** [comment] 2017-06-04 20:34
Thanks for reporting the issue. A similar one has been reported in the gitter chat. The reporter managed to install it by temporarily disabling the antivirus. This should be safe if, as it is likely, it is a false positive. There are many reports of false positive virus detections in [winpython](https://www.google.com/search?q=virus+winpython&oq=virus+winpython) (the base of the bundle). However, I am currently out of the office and I don't have the means to fully confirm if this is the case (can anybody help with this?).

You could check the sha256 sum of the file that should be ```cca057561c93a6953b123f1d81d575f69717dc14cb4cb61646c931ef6b46bda7``` to detect if it has been altered. From now on we will publish the hash in the GitHub release page.

On the other hand, to stay fully on the safe side, you could install hyperspy using anaconda instead. Usually it is a little bit more involved, but maybe not when the bundle is mistaken for a virus.

**Comment by matthcarpenter** [comment] 2017-06-04 20:44
Thank you for the response Francisco.  I downloaded and checked the sha256 on another computer, it does match the sum you posted.  As I cannot disable the antivirus on my organization's computer, I'll try installing via anaconda instead.

**Comment by francisco-dlp** [comment] 2017-06-04 20:56
Thanks. I'll reopen the issue is order to make it more visible to others being hit by it. We'll close it once we find a solution, probably after reporting it to Symantec.

**Comment by francisco-dlp** [comment] 2017-06-16 16:04
I have installed the bundle without issues in W7 with up-to-date McAfee antivirus. I have also scanned the computer after installation with Symantec's Norton Security Scan and again no virus was detected. Therefore, as it looks like this is not a general issue and that it may have been fixed by Symantec already, I'll close it.

**Closed as completed by francisco-dlp** 2017-06-16 16:04 UTC
