### ISSUE TITLE
eels.remove_background() removes signal axes information

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2122] opened 2019-01-24 08:03 UTC
Minimum working example:
```
s = hs.datasets.artificial_data.get_core_loss_eels_signal()
s.plot()
s.remove_background(signal_range=(600.,650.)).plot()
```
It also renders background subtraction entirely wrong, at least on my data (difficult to show with the artificial data since the background has already been removed).

**Comment by ericpre** [comment] 2019-01-24 22:43
Duplicate of #2104.

**Closed as completed by ericpre** 2019-01-24 22:43 UTC
