### ISSUE TITLE
Ambiguity on the Signal axes argument

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2345] opened 2020-03-31 13:22 UTC
This issue is about "proper" ways of automatically defining a new `axes_manager` based on a previous signal.

From the [documentation on **Signal Initialisation**](http://hyperspy.org/hyperspy-doc/current/user_guide/tools.html#signal-initialization), one can define a list of dicts to describe axes for input into the `BaseSignal` class: 
```python
dict0 = {'size': 10, 'name':'Axis0', 'units':'A', 'scale':0.2, 'offset':1}
# (This following line is actually missing from the docs)
dict1 = {'size': 20, 'name':'Axis1', 'units':'A', 'scale':0.2, 'offset':1}
s = hs.signals.BaseSignal(np.random.random((10,20)), axes=[dict0, dict1])
```
There are a few problems I have with this. Some of these might affect the nonlinear axes PRs (#1927), and I would value the input from @ericpre and @jlaehne on the following:

1. This is in disagreement with the BaseSignal docstring, which claims `axes` should be a dict (also see point 3):
```python
axes : dict, optional
    Dictionary to define the axes (see the documentation of the
    :py:class:`~hyperspy.axes.AxesManager` class for more details).
```
2. It is not well-documented. There exists no method I'm aware of to generate such a list from an existing axes_manager. The only relevant part of the `hyperspy.axes.AxesManager` docstring, which the reader is referred to in the docstring above, is `Init signature: hyperspy.axes.AxesManager(axes_list)`. This implies some sort of list, but with no details on how one should do that or if one should be using the AxesManager class directly.

3. There is also the `AxesManager` method `s.axes_manager.as_dictionary()`, which does not work for the `BaseSignal` `axes` above. For the above signal, it returns the following:
```python
{'axis-0': {'name': 'Axis0', 'scale': 0.2, 'offset': 1.0, 'size': 10, 'units': 'A', 'navigate': False},
 'axis-1': {'name': 'Axis1', 'scale': 0.3, 'offset': 4.0, 'size': 20, 'units': 'A', 'navigate': False}}
```
It would be nice to be able to use the above method (or something similar) when initialising a new signal based on an old one, although `s._deepcopy_with_new_data()` might do this:
`s2 = s.__class__(data, axes = s.axes_manager.as_dictionary())`.

4. There is no check to see that the axes_manager size matches the signal shape. I'd argue that a warning should be printed, and that the axes_manager size should change to fit the data (possible error raised for FunctionalDataAxis?)

### Notes
There exists `axes_manager1.update_axes_attributes_from(axes)`. This is great, and should be documented better. 
It would be nice to know if overwriting the axes manager of one signal with another like  `s.axes_manager  = s2.axes_manager.copy()` is safe and a good idea.

### Suggestions

1. Get rid of dicts, only use lists of DataAxis objects. Update the docs with this.
2. Introduce `AxesManager.get_axes_list()` or similar named method.
3. Introduce AxesManager under its own heading in the [`Tools: the Signal class` docs](http://hyperspy.org/hyperspy-doc/current/user_guide/tools.html). Introduce LinearDataAxis and FunctionalDataAxis there.

**Comment by jlaehne** [comment] 2020-03-31 20:14
Your example of `s.axes_manager.as_dictionary()` is a nested dictionary, so that is what I would expect from the command.

Of course there should be clarity in the documentation concerning the axes initialization.

Concerning Suggestion 1:
The dictionaries are important for the IO in `io_plugins/hspy.py`.
In #2304, I'm still fighting with how to adapt that for the new axes types (see also https://github.com/ericpre/hyperspy/pull/11)

Concerning Suggestion 2:
I don't see a problem in providing such a method, but I am not deep enough into how the code developed and where the choices for what you describe come from.

Concerning Suggestion 3:
This is more or less what I did to document the non linear axes types in #1927 (https://github.com/hyperspy/hyperspy/pull/1927/commits/83dc60099b7dfda097a3cb38ee9c1a1476ca203a)
I even added a separate `axes.rst` with the title `Axes handling` between `Getting started` and `Tools`, because with the different axes types it would overload the other pages and I think axes are an essential enough part of hyperspy to warrant their own page.

**Comment by thomasaarholt** [comment] 2020-05-07 15:05
I think we need to work at this from the point of view of the Axes Manager, and then use those conclusions to improve the Signal `axes` argument. I would like to make DataAxis and AxesManager more useful entities on their own. Here are some thoughts on AxesManager and DataAxis:

#### Creating an AxesManager
The AxesManager class does not like to take a list of DataAxis, when (imo) it should. I still don't know what this list should be of:
```python
from hyperspy.axes import AxesManager, DataAxis

axes = [DataAxis(size=128) for i in range(3)]
am = AxesManager(axes_list=axes)

TypeError: _append_axis() argument after ** must be a mapping, not DataAxis
```

<details>
<summary>Full error</summary>

```python 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-3c6ee4a87cde> in <module>
----> 1 am = AxesManager(axes_list=axes)

c:\users\thomasaar\documents\github\hyperspy\hyperspy\axes.py in __init__(self, axes_list)
    803             obj : The AxesManager that the event belongs to.
    804             """, arguments=['obj'])
--> 805         self.create_axes(axes_list)
    806         # set_signal_dimension is called only if there is no current
    807         # view. It defaults to spectrum

c:\users\thomasaar\documents\github\hyperspy\hyperspy\axes.py in create_axes(self, axes_list)
    990             axes_list.sort(key=lambda x: x['index_in_array'])
    991         for axis_dict in axes_list:
--> 992             self._append_axis(**axis_dict)
    993 
    994     def _update_max_index(self):

TypeError: _append_axis() argument after ** must be a mapping, not DataAxis
```
</details>

#### DataAxis `size`
Current behaviour is so that one can change `s.data.shape` without s.axes_manager responding to this change. This can lead to errors, like below. A question for @ericpre, @jlaehne or @francisco-dlp: How necessary is the `size` argument for DataAxis and FunctionalDataAxis? I would personally prefer it to be optional, so that one can initialise an AxesManager without it, and then it should (imo) use the Signal data shape as size. Not sure what should be the case if the shapes disagree after being explicitly set.
```
s = hs.signals.Signal1D(np.zeros(1000))
print(s.axes_manager[-1].size) # 1000
s.data = np.zeros(100)
print(s.axes_manager[-1].size) # 1000
s.plot()
```
I don't feel very strongly about this, but I think it would be nice to agree on what the behaviour should be.

#### Iterable `DataAxis`?
Finally, mainly writing this so I dont forget. It could be nice if (if we keep explicitly setting the `size`) to make DataAxis iterable, allowing:

```python
for index, value in enumerate(DataAxis(...)):
```

**Comment by jlaehne** [comment] 2020-05-11 08:06
> #### Creating an AxesManager
From my pov, we could add that way to initialize axes manager

> #### DataAxis `size`
I don't know how feasible it is to run an axis update automatically, when the shape of data changes. Also, if we create some automatism, it might prompt people to do so without thinking about the consequences for the axes. 

The new `DataAxis` relies on an explicit axis-vector, so the size is just the length of that vector. We would need to raise an error if the size of the data changes.

`LinearDataAxis` and `FunctionalDataAxis` are initialized with offset, scale and size. So one could theoretically change the size automatically, but it would imply that you pad or cut at the higher index side of the axis values, which might not always be the intended behavior.

**Comment by francisco-dlp** [comment] 2020-05-13 09:34
This thread contains interesting ideas on how to improve ``AxesManager``. It would be good to summarize them in a checklist so that we can turn them easily to actions (PRs).

**Comment by jlaehne** [comment] 2020-05-14 17:50
Yes, but I would favor getting non_uniform_axis merged before starting new workshops on the axes_manager.

**Comment by jlaehne** [comment] 2020-05-31 22:09
> #### Creating an AxesManager
> 
> The AxesManager class does not like to take a list of DataAxis, when (imo) it should. I still don't know what this list should be of:
 
@thomasaarholt  Your example should be working now in #2304 (just changing `DataAxis` to the new `UniformDataAxis` when initializing with only the `size` argument):
```python
from hyperspy.axes import AxesManager, UniformDataAxis
axes = [UniformDataAxis(size=128) for i in range(3)]
am = AxesManager(axes_list=axes)
```

AxesManager should now be able to handle either a list of dictionaries or a list of axes objects. Feedback appreciated.

**Comment by ericpre** [comment] 2022-04-30 10:01
Closing as this was mostly done in the last release.

**Closed as completed by ericpre** 2022-04-30 10:01 UTC
Labels: type: enhancement
