### ISSUE TITLE
edsmodel automatically computes lazy array when auto_add_lines=True

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2806] opened 2021-08-09 19:48 UTC
[This line](https://github.com/hyperspy/hyperspy/blob/e7a0267b8e3757b1cce13763c06eb014a55af7f3/hyperspy/models/edsmodel.py#L253) causes lazy EDS signals to be computed during `s.create_model(auto_add_lines=True)`. 

I've copied the example I used to discover this below. This also explains why EDSModels sometimes seem to take a very long time to create.

A look through [history](https://github.com/hyperspy/hyperspy/commit/25ebdd361e1211f537d76d1cebd302a4019dbcea#diff-8802d8e852213e71ea71b1014e01aa97946733137e5fb14a0eaf739590dc5a22L238) seems to imply that this was used to give the model good initial values based on the height of the line? I suggest we either make this an optional method the user can call, or at least remove it in the case of a lazy signal.

```python
import hyperspy.api as hs
from hyperspy.axes import UniformDataAxis
import dask.array as da

from hyperspy.datasets.example_signals import EDS_SEM_Spectrum
from hyperspy._signals.eds_sem import LazyEDSSEMSpectrum
from hyperspy._signals.signal2d import LazySignal2D

s = EDS_SEM_Spectrum()
data = s.data
axis = UniformDataAxis(offset = -0.1, scale = 0.01, size = 1024, units="keV")
s2 = LazyEDSSEMSpectrum(data, axes = [axis])
s2.add_elements(s.metadata.Sample.elements)
s2.set_microscope_parameters(beam_energy=10.)

nav = LazySignal2D(da.random.random((1000, 1000)))
s = s2 * nav.T

m = s.create_model() # interrupt this after a few seconds, note the presence of `self.compute()` in 5th error
```

**Comment by ericpre** [comment] 2021-08-15 11:02
Duplicate of https://github.com/hyperspy/hyperspy/issues/2436.

**Closed as completed by ericpre** 2021-08-15 11:02 UTC
