### ISSUE TITLE
Opening a 4 GB dm4 - File

### ISSUE THREAD

**Issue by mgrove-wwu** [hyperspy/hyperspy#2253] opened 2019-09-09 12:22 UTC
Hello,

I am currently experiencing an issue for opening a dm4 file.
Actually, i was able to open and also calculate a lot of stuff for the mentioned exact same dm4-file with a previous anaconda environment for hyperspy. 

Now i did set up a completely fresh anaconda environment and as always only for hyperspy to single out errors, but the weird thing is after i finished the environment set up i was not able to open the dm4 file again.
The size of the dm4-file is 4,3 GB. I already looked into the closed issues for opening large dm4 files but the error message i got was different as it seems.
Executing the following code results in the also following traceback:
`hs.load(filenames='Name_Of_File.dm4')`

```---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-14-6cb1c508cff9> in <module>
----> 1 hs.load(filenames='PdNiP/EELS Spectrum Image.dm4')

~/anaconda3/envs/Hyperspy/lib/python3.7/site-packages/hyperspy/io.py in load(filenames, signal_type, stack, stack_axis, new_axis_name, lazy, convert_units, **kwds)
    279             objects = [load_single_file(filename, lazy=lazy,
    280                                         **kwds)
--> 281                        for filename in filenames]
    282 
    283         if len(objects) == 1:

~/anaconda3/envs/Hyperspy/lib/python3.7/site-packages/hyperspy/io.py in <listcomp>(.0)
    279             objects = [load_single_file(filename, lazy=lazy,
    280                                         **kwds)
--> 281                        for filename in filenames]
    282 
    283         if len(objects) == 1:

~/anaconda3/envs/Hyperspy/lib/python3.7/site-packages/hyperspy/io.py in load_single_file(filename, **kwds)
    316     else:
    317         reader = io_plugins[i]
--> 318         return load_with_reader(filename=filename, reader=reader, **kwds)
    319 
    320 

~/anaconda3/envs/Hyperspy/lib/python3.7/site-packages/hyperspy/io.py in load_with_reader(filename, reader, signal_type, convert_units, **kwds)
    323     lazy = kwds.get('lazy', False)
    324     file_data_list = reader.file_reader(filename,
--> 325                                         **kwds)
    326     objects = []
    327 

~/anaconda3/envs/Hyperspy/lib/python3.7/site-packages/hyperspy/io_plugins/digital_micrograph.py in file_reader(filename, record_by, order, lazy, optimize)
   1026     with open(filename, "rb") as f:
   1027         dm = DigitalMicrographReader(f)
-> 1028         dm.parse_file()
   1029         images = [ImageObject(imdict, f, order=order, record_by=record_by)
   1030                   for imdict in dm.get_image_dictionaries()]

~/anaconda3/envs/Hyperspy/lib/python3.7/site-packages/hyperspy/io_plugins/digital_micrograph.py in parse_file(self)
     86             number_of_root_tags,
     87             group_name="root",
---> 88             group_dict=self.tags_dict)
     89 
     90     def parse_header(self):

~/anaconda3/envs/Hyperspy/lib/python3.7/site-packages/hyperspy/io_plugins/digital_micrograph.py in parse_tags(self, ntags, group_name, group_dict)
    215                     ntags=ntags,
    216                     group_name=tag_name,
--> 217                     group_dict=group_dict[tag_name])
    218             else:
    219                 _logger.debug('File address:', self.f.tell())

~/anaconda3/envs/Hyperspy/lib/python3.7/site-packages/hyperspy/io_plugins/digital_micrograph.py in parse_tags(self, ntags, group_name, group_dict)
    215                     ntags=ntags,
    216                     group_name=tag_name,
--> 217                     group_dict=group_dict[tag_name])
    218             else:
    219                 _logger.debug('File address:', self.f.tell())

~/anaconda3/envs/Hyperspy/lib/python3.7/site-packages/hyperspy/io_plugins/digital_micrograph.py in parse_tags(self, ntags, group_name, group_dict)
    215                     ntags=ntags,
    216                     group_name=tag_name,
--> 217                     group_dict=group_dict[tag_name])
    218             else:
    219                 _logger.debug('File address:', self.f.tell())

~/anaconda3/envs/Hyperspy/lib/python3.7/site-packages/hyperspy/io_plugins/digital_micrograph.py in parse_tags(self, ntags, group_name, group_dict)
    114         for tag in range(ntags):
    115             _logger.debug('Reading tag name at address: %s', self.f.tell())
--> 116             tag_header = self.parse_tag_header()
    117             tag_name = tag_header['tag_name']
    118 

~/anaconda3/envs/Hyperspy/lib/python3.7/site-packages/hyperspy/io_plugins/digital_micrograph.py in parse_tag_header(self)
    451 
    452     def parse_tag_header(self):
--> 453         tag_id = iou.read_byte(self.f, "big")
    454         tag_name_length = iou.read_short(self.f, "big")
    455         tag_name = self.read_string(tag_name_length)

~/anaconda3/envs/Hyperspy/lib/python3.7/site-packages/hyperspy/misc/io/utils_readfile.py in read_byte(f, endian)
    238         elif endian == 'little':
    239             s = L_byte
--> 240         return s.unpack(data)[0]
    241 
    242 

error: unpack requires a buffer of 1 bytes
```

As shown it seems to have an issue unpacking the data which was perhaps read as little endian byte encoding if i am not wrong in understanding the underlying code. Now i am quite lost in how to approach this issue. As mentioned above, in a previous hyperspy version the file was definitely not generating an error as it does now.

If you guys could help me one hopefully last time, i seem to be finishing my masterthesis on EELS analysis soon with your module and especially your awesome support!

Thanks a lot in advance! Sincerely,
Max

Off topic: I have written a code for automated plasmon fitting in my thesis and if there is ANY interest, i could stay in contact with you guys to include it in hyperspy as an additional library even though it would still need work and adjustments for modularity reasons!

**Comment by francisco-dlp** [comment] 2019-09-10 10:44
Nothing has changed in the code since 1 year when support for big files was implemented, so your issue must be due to changes in external libraries. Could you share the file with us so that we can identify the issue?

**Comment by mgrove-wwu** [comment] 2019-09-10 12:21
Do you have any preferences for the file sharing service? I would strongly! prefer a service with encryption, though, as it is confidential data as far as i know.

As for the file: I am currently testing another file copy of the same data, which hopefully works. We thought that the file generating the issue was our only copy, but as it seems I might have been wrong. 

Thanks for your fast answer, though!

**Comment by francisco-dlp** [comment] 2019-09-10 12:25
No, I don't have any preference or advice on how to share your file. However, if you confirm that the issue is that your copy of the file was corrupted, then there is no need to share it at all. If that happens to be the case, please think on closing the issue.

**Comment by mgrove-wwu** [comment] 2019-09-10 12:26
Thanks again for the fast reply. I will comment after testing today and of course close it if there is no relation to hyperspy.

**Comment by mgrove-wwu** [comment] 2019-09-10 14:25
My apologies for opening this thread. It seems that the other copy is not corrupted and working totally as intended! I am closing it. Sorry for the inconveniences!

PS: Anyway thanks a lot for the patience with me!

**Closed as completed** 2019-09-10 14:25 UTC
