### ISSUE TITLE
Determine zeta-factors from known sample

### ISSUE THREAD

**Issue by siriagus** [hyperspy/hyperspy#1056] opened 2016-06-03 13:49 UTC
There should be a function for facilitating the determination of the zeta-factors from a sample with known composition, thickness and dose. I have a working function for this, but it need a bit of tidying up before I can make a PR.

**Comment by k8macarthur** [comment] 2016-06-07 06:34
I thought about this. However the issue is that there are several different geometry of samples which could be used for determining thickness and therefore z-factors. Do you cater for all of them? Or do you just include the one you know? How were you thinking of doing it?

**Comment by siriagus** [comment] 2016-06-07 12:42
@k8macarthur The function calculate the zeta factors based on a known thickness. The thickness can be given as a float or a signal. For a thin-film with only one measurement (average) for thickness a float would be used. If your thickness varies a lot, a signal (or image) have to be made describing the sample where each pixel corresponds to the same pixel in your spectrum image. This map could be constructed "manually". 

Not sure what you ment, since thickness has to be determined independently. One solution is to estimate thickness from an EELS map taken at the same position and with same step size as the EDS map could be used. For a nanowire, thickness could be calculated based on orientation and projected width.

This function takes in a thickness map, it doesn't create one, so unsure what you meant. Once the thickness is known, the zeta-factor could be calculated. Please clarify if I misunderstood! :)

**Comment by k8macarthur** [comment] 2016-07-06 12:42
Sorry for forgetting to get back to this. I think you make sense. If thickness can be provided as a map or a profile I guess that keeps it general. I'll try and have a look at the actual maths in the next few weeks.

**Comment by tjof2** [comment] 2020-08-25 08:52
Closing based on comments in #1057 unless there is a demand to reopen.

**Closed by tjof2** 2020-08-25 08:52 UTC
Labels: release: next minor, type: New feature
