### ISSUE TITLE
remove_background GUI cannot be closed.

### ISSUE THREAD

**Issue by jat255** [hyperspy/hyperspy#561] opened 2015-06-03 17:28 UTC
I don't think this is related to #560, but I have also noticed some undesired behavior when using the `remove_background()` function to start the GUI. I assume this has something to do with my setup, but I am using all the latest packages for dependencies, and the 0.8 release version of Hyperspy.

When I do an interactive background removal, the window that controls the process and allows me to choose a background model remains behind after clicking 'OK'. I cannot get rid of it without restarting the kernel. See the following video for an example:

![remove_background_persist](https://cloud.githubusercontent.com/assets/1278301/7966515/9b749874-09f2-11e5-86a5-5f514926b26d.gif)

**Comment by francisco-dlp** [comment] 2015-06-03 17:33
Great bug report! However, here we have two bugs in one single issue, could you submit separate issues for each of them?

**Comment by jat255** [comment] 2015-06-03 17:36
Sorry, sure thing! I'll open another one for the background scaling issue.

**Comment by francisco-dlp** [comment] 2015-06-04 17:47
I cannot reproduce this in Linux using the latest packages is Anaconda.

**Comment by vidartf** [comment] 2015-06-04 18:19
Cannot reproduce on Windows 7 (64-bit) using WinPython 64-bit. Does this happen no matter what console you use (notebook/qtconsole) ?

**Comment by jat255** [comment] 2015-06-18 18:39
Sorry for the delay on getting back to this. I can confirm it doesn't happen on the `wx` backend, so it appears to be some sort of bug with my PyQt setup, it seems.

**Comment by vidartf** [comment] 2015-06-18 20:15
Have you checked if it happens for both PyQt and PySide?

**Comment by jat255** [comment] 2015-06-18 20:21
Is there a simple way to choose whether PyQt or PySide is used? I always thought you could only choose `qt4` as the backend.

**Comment by vidartf** [comment] 2015-06-18 20:31
Possible solutions from google:
```python 
matplotlib.use('Qt4Agg')
matplotlib.rcParams['backend.qt4']='PySide'
```

**Comment by jat255** [comment] 2015-06-18 21:02
Hmm, I'm not sure if that command had any impact. When I ran from a notebook, the problem persisted. When running from a console (just `hyperspy --toolkit qt4` from the command line), the background selection dialog looks different and runs as expected (closing when it should).

FYI, I have PySide (v1.2.2) and PyQt4 (v4.11.3) installed.

I'm guessing something is being loaded in the notebook script that's causing the issue?

**Comment by jat255** [comment] 2015-06-18 21:02
Also, I tried running in a qtconsole, but I got this error (which may be unrelated):
```python
ImportError:
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7 or PySide >= 1.0.3 is available,
    and only one is imported per session.

    Currently-imported Qt library:   'pyqtv1'
    PyQt4 installed:                 True
    PySide >= 1.0.3 installed:       True
    Tried to load:                   ['pyqt']
```

**Comment by vidartf** [comment] 2015-06-18 21:06
Try setting `backend.qt4` to `PySide` in the matplotlib RC file. Then you won't have to worry about load order.

**Comment by jat255** [comment] 2015-06-18 21:12
Ok, I tried that, and changing it from `PyQt4` to `PySide` did not seem to have any effect. Since I ran the notebook from the command line, I did observe the following output that appears when I try to click the close button on the blank dialog:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\Python279-x64\lib\site-packages\traitsui\wx\ui_live.pyc in _on_close_page(self=<traitsui.wx.ui_live.LiveWindow object>,
event=<wx._core.CloseEvent; proxy of <Swig Object of type 'wxCloseEvent *' at 0x229d10> >)
    328         """ Handles the user clicking the window/dialog "close" button/icon.
    329         """
--> 330         if self.ui.view.close_result == False:
        self.ui.view.close_result = undefined
        global False = undefined
    331             self._on_cancel( event )
    332         else:

AttributeError: 'NoneType' object has no attribute 'view
```

**Comment by jat255** [comment] 2015-06-19 22:16
So I think I've narrowed this down to some sort of error in `traitsui`, having to do with `wx`.

I downloaded a new installation of Winpython, and added `traitsui` and `traits` to it via `pip`. I then cloned @to266's ipython3 branch (so I could use the new Winpython) and installed it into the winpython distribution with `pip install -e`.

## Without WX (problem 1):<a name="heading1"></a>

Using this setup, I started up a notebook (or a qtconsole, doesn't matter) and I get a setup of windows when subtracting background that looks like:

![001-withoutwx](https://cloud.githubusercontent.com/assets/1278301/8263777/14b5fd8e-16ac-11e5-8d91-5f8069385c42.png)


This causes another strange behavior however, in that if I drag around on the plot for a while (which sometimes you do when trying to fit a particularly fiddly background), the remove background window disappears. There's no output in the terminal, just a silent failure. This makes it so you have to try again and try to subtract before the window disappears, or just use the command line version of the command. See this is action below:

![001-withoutwx](https://cloud.githubusercontent.com/assets/1278301/8263848/ff9ca500-16ac-11e5-9e70-fff28a867f4a.gif)

## With WX installed (problem 2):

If I install wx (using the windows installer from [wxpython.org](http://www.wxpython.org/download.php#msw)), the behavior goes back to what I described before, even though I am using the qt backend.

These are the commands that I am using, after starting the console with `hyperspy qtconsole`:

```python
# %hyperspy qt4
import numpy as np
import hyperspy.hspy as hs
%matplotlib qt4
import matplotlib.pyplot as plt

s = hs.load("SI 1 - EELS.dm3")
s.remove_background()
```

I've made no reference to `wx` other than having it installed, and haven't changed any of the defaults, but now the behavior of the traits window has changed. It appears different, and now will not disappear after running (but at least it doesn't arbitrarily disappear, now...):

![002-withwx-with-qtconsole](https://cloud.githubusercontent.com/assets/1278301/8263983/bba8b22e-16ae-11e5-926f-fd1991fdd236.gif)


## Other notes:

Finally, I noticed that if I run just `hyperspy` from the command prompt (with wx installed), the window behaves as in problem 1, above. So it appears that something about loading the qtconsole and the notebook engages some wx code, which then triggers this bug?

Sorry for all the rambling, I'm just trying to diagnose this behavior as much as possible. The fact that I'm seeing it in a brand new Winpython installation as well leads me to believe that it is not a problem with my installation, but maybe a conflict with `traitsui`

**Comment by vidartf** [comment] 2015-06-21 08:57
It might be that traitsui is getting confused about which backend it should
use, especially that it conflicts with what MPL/IPython is using (why else
would you be getting wx errors when running Qt?). Not sure if this is a
hyperspy setting, or if it should be set somewhere else though.

**Comment by jat255** [comment] 2015-06-22 16:47
So I've done some more testing trying to nail this bug down (it actually appears that there might be two different things going on here: 

1. One is that with the `qt4` backend, the traitsui background subtraction window disappears arbitrarily. I'm not sure if this is Hyperspy's fault or not. 
2. The other is that even when you ask for the `qt4` backend, you get the `wx` backend for traitsui windows if you're using the `qtconsole` or the `notebook` commands.

Regarding point 2 above, I've done some digging and an error occurs in [line 49 of the gui `_init_` code](https://github.com/hyperspy/hyperspy/blob/master/hyperspy/gui/__init__.py#L49) when starting with the qt4 toolkit. The code correctly recognizes the `qt4` toolkit argument, but when it tries to set it in line 28, it gets a `ValueError: cannot set toolkit to qt4 because it has already been set to wx`. It appears that `traits` has already decided which toolkit it is going to use at this point.

Exploring further, when running `hyperspy qtconsole`, it appears that the `ETSConfig.toolkit` value is  correctly set within the `bin/hyperspy` script at [line 174](https://github.com/hyperspy/hyperspy/blob/master/bin/hyperspy#L174) (which I confirmed with print statements). When I go to `import hyperspy.hspy` in the actual qtconsole though, I get the error described in the previous paragraph. Somewhere between line 174 and importing `hspy`, the `ETSToolkit` is set back to `wx`, but I cannot figure out where.

I did figure out one solution to this problem, but I'm not sure if it has any other repercussions, which is to add the following line to `./bin/hyperspy` right after [line 174](https://github.com/hyperspy/hyperspy/blob/master/bin/hyperspy#L174). With this in place, the ETS toolkit is set correctly and remains `qt4` even if you have `wx` installed. Bug 1 from above still remains though.

```python
os.environ['ETS_TOOLKIT'] = toolkit
```

Below are some of the results of my testing. The highlighting with 1 or 2 exclamation points matches bugs 1 and 2 above. When both toolkits are successfully set to `wx`, the persistent window bug doesn't happen.

With `wx` installed:
-----

Starting/ipython command | Background subtraction window result | HyperSpy GUI plotting toolkit | ETSConfig.toolkit
------------ | ------------- | --------------------| ----------------
`hyperspy`<br> `%hyperspy` |:heavy_exclamation_mark: Small window (qt); disappears too early | `qt4` | `qt4`
`hyperspy --toolkit qt4`<br> `%hyperspy` |:heavy_exclamation_mark: Small window (qt); disappears too early | `qt4` | `qt4`
`hyperspy --toolkit wx`<br> `%hyperspy` | Large window (wx); disappears as expected | `wx` | `wx`
---------------| --------------- | --------------- | ---------------
`hyperspy qtconsole`<br> `%hyperspy` |:bangbang: Large window; never disappears | `qt4` | `wx`
`hyperspy qtconsole --toolkit qt4`<br> `%hyperspy` |:bangbang: Large window; never disappears | `qt4` | `wx`
`hyperspy qtconsole --toolkit wx`<br> `%hyperspy`<sup>[\[1\]](#matplotlibMagic1)</sup>  | Large window; disappears as expected | `wx` | `wx`
`hyperspy qtconsole --toolkit wx`<br> `%hyperspy` (correcting %matplotlib to wx) | Large window; disappears as expected | `wx` | `wx`
---------------| --------------- | --------------- | ---------------
`hyperspy notebook`<br> `%hyperspy` |:bangbang: Large window; never disappears | `qt4` | `wx`
`hyperspy notebook --toolkit qt4`<br> `%hyperspy` |:bangbang: Large window; never disappears | `qt4` | `wx`
`hyperspy notebook --toolkit wx`<br> `%hyperspy`<sup>[\[2\]](#matplotlibMagic2)</sup> |:bangbang: Large window; never disappears | `qt4` | `wx`
`hyperspy notebook --toolkit wx`<br><br> `import numpy as np`<br> `import hyperspy.hspy as hs`<br> `%matplotlib wx`<br> `import matplotlib.pyplot as plt` (correcting %matplotlib to wx) | Large window; disappears as expected | `wx` | `wx`


Notes
---
<a name="matplotlibMagic1">[1]</a>: The `%hyperspy` magic actually adds the line `%matplotlib qt4` even when you specify `wx` as the toolkit on the command line, instead of `%matplotlib wx`, as one might expect. It does not seem to have a deleterious effect though, as ipython complains: `Warning: Cannot change to a different GUI toolkit: qt4. Using wx instead.`
<a name="matplotlibMagic2">[2]</a>: When running in a notebook, it appears the `%hyperspy` magic does set the matplotlib backend to `qt4`, overriding the setting specified on the command line. This leads to the unwanted behavior and the GUI using the `qt4` backend instead of `wx`. Manually executing the commands (as in the next example) corrects this.


Without `wx` installed:
-----

Starting/ipython command | Background subtraction window result | HyperSpy GUI plotting toolkit | ETSConfig.toolkit
------------ | ------------- | --------------------| ----------------
`hyperspy`<br> `%hyperspy` |:heavy_exclamation_mark: Small window; disappears too early | `qt4` | `qt4`
`hyperspy --toolkit qt4`<br> `%hyperspy` |:heavy_exclamation_mark: Small window; disappears too early | `qt4` | `qt4`
`hyperspy --toolkit wx`<br> `%hyperspy` | Matplotlib `wx` `ImportError` | `--` | `--`
---------------| --------------- | --------------- | ---------------
Same | results | with | qtconsole
---------------| --------------- | --------------- | ---------------
Same | results | with | notebook, except...
`hyperspy notebook --toolkit wx`<br> `%hyperspy`<sup>[\[3\]](#matplotlibMagic3)</sup> |:heavy_exclamation_mark: Small window; disappears too early | `qt4` | `qt4`

<a name="matplotlibMagic3">[3]</a>: I would expect this command to give an error, but again, it appears that the `%matplotlib qt4` magic command that is brought in by `%hyperspy` overrides the toolkit selection from the command line.

**Comment by jat255** [comment] 2015-06-22 17:03
I can also add that the `qt4` window seems to disappear only for Power Law fitting, not for any of the other functions, although I'm not sure what that means, exactly...

**Comment by to266** [comment] 2015-06-23 10:04
Wow, thanks for the thorough testing. I'm not sure I'll be able to help, but will try to have a look at the discussion.

Two notes, though:

 1. You can pass the toolbox to the `%hyperspy` magic - if it's not (i.e. in all your examples), it just looks for the default one, set in the hyperspy settings.
 2.  We've been considering getting rid of `traitsui` altogether - it's the last thing keeping hyperspy from migrating to python3. By considering I mean we all talked about that and never actually started doing anything :) Do you think that might reduce the clutter / confusion with the toolboxes?

**Comment by jat255** [comment] 2015-06-23 17:48
@francisco-dlp: I just downloaded Anaconda (on windows) and did an installation of the latest Hyperspy master. The background subtraction window disappearing still occurs for me.

Do you mind posting the output of `conda list` from your Hyperspy environment? I'm curious if there's a package difference or something that's causing this bug. Hopefully it's not just Windows being Windows (although I wouldn't be surprised...)

To create this environment, I downloaded a new Anaconda (64 bit, 2.7.9), cloned the root environment, installed `traits`, `traitsui`, and `wxpython` using `conda install` and then cloned the latest hyperspy master and installed with `pip install -e ./`

Mine is:
```sh
[hyperspy] C:\tmp>conda list
# packages in environment at C:\Anaconda\envs\hyperspy:
#
_license                  1.1                      py27_0
anaconda                  2.2.0                np19py27_0
argcomplete               0.8.4                    py27_0
astropy                   1.0.1                np19py27_0
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.8.1                np19py27_0
beautiful-soup            4.3.2                    py27_1
beautifulsoup4            4.3.2                     <pip>
binstar                   0.10.1                   py27_3
bitarray                  0.8.1                    py27_1
blaze                     0.7.3                     <pip>
blaze-core                0.7.3                np19py27_0
blz                       0.6.2                np19py27_0
bokeh                     0.8.1                np19py27_1
boto                      2.36.0                   py27_0
cdecimal                  2.3                      py27_1
certifi                   14.05.14                 py27_0
cffi                      0.9.2                    py27_0
clyent                    0.3.4                    py27_0
colorama                  0.3.3                    py27_0
conda-build               1.11.0                   py27_0
conda-env                 2.2.3                    py27_0
configobj                 5.0.6                    py27_0
cryptography              0.8                      py27_1
cython                    0.22                     py27_0
cytoolz                   0.7.2                    py27_0
datashape                 0.4.4                np19py27_1
decorator                 3.4.2                    py27_0
docutils                  0.12                     py27_1
dynd-python               0.6.5                np19py27_0
enum34                    1.0.4                    py27_0
fastcache                 1.0.2                    py27_0
flask                     0.10.1                   py27_1
funcsigs                  0.4                      py27_0
futures                   2.2.0                    py27_0
gevent                    1.0.1                    py27_0
gevent-websocket          0.9.3                    py27_0
glueviz                   0.4.0                np19py27_1
greenlet                  0.4.5                    py27_0
grin                      1.2.1                    py27_2
h5py                      2.4.0                np19py27_0
hyperspy (c:\anaconda\hyperspy) 0.8 53 g78dbd8f           <pip>
ipython                   3.2.0                    py27_0
ipython-notebook          3.2.0                    py27_0
ipython-qtconsole         3.2.0                    py27_0
itsdangerous              0.24                     py27_0
jdcal                     1.0                      py27_0
jedi                      0.8.1                    py27_0
jinja2                    2.7.3                    py27_2
jsonschema                2.4.0                    py27_0
launcher                  1.0.0                         1
llvmlite                  0.2.2                    py27_1
lxml                      3.4.2                    py27_0
markupsafe                0.23                     py27_0
matplotlib                1.4.3                np19py27_1
menuinst                  1.0.4                    py27_0
mistune                   0.6                      py27_0
mock                      1.0.1                    py27_0
multipledispatch          0.4.7                    py27_0
networkx                  1.9.1                    py27_0
nltk                      3.0.2                np19py27_0
node-webkit               0.10.1                        0
nose                      1.3.4                    py27_1
numba                     0.17.0               np19py27_0
numexpr                   2.3.1                np19py27_0
numpy                     1.9.2                    py27_0
odo                       0.3.1                np19py27_0
openpyxl                  1.8.5                    py27_0
pandas                    0.16.2               np19py27_0
patsy                     0.3.0                np19py27_0
pep8                      1.6.2                    py27_0
pillow                    2.8.2                    py27_0
pip                       7.0.3                    py27_0
ply                       3.4                      py27_0
psutil                    2.2.1                    py27_0
py                        1.4.26                   py27_0
pyasn1                    0.1.7                    py27_0
pycosat                   0.6.1                    py27_0
pycparser                 2.10                     py27_0
pycrypto                  2.6.1                    py27_3
pyface                    4.4.0                    py27_0
pyflakes                  0.8.1                    py27_0
pygments                  2.0.2                    py27_0
pyopenssl                 0.14                     py27_0
pyparsing                 2.0.3                    py27_0
pyqt                      4.10.4                   py27_1
pyreadline                2.0                      py27_0
pytables                  3.1.1                np19py27_1
pytest                    2.6.4                    py27_0
python                    2.7.10                        0
python-dateutil           2.4.2                    py27_0
pytz                      2015.4                   py27_0
pywin32                   219                      py27_0
pyyaml                    3.11                     py27_1
pyzmq                     14.7.0                   py27_0
requests                  2.7.0                    py27_0
rope                      0.9.4                    py27_1
runipy                    0.1.3                    py27_0
scikit-image              0.11.2               np19py27_0
scikit-learn              0.15.2               np19py27_0
scipy                     0.15.1               np19py27_0
setuptools                17.1.1                   py27_0
six                       1.9.0                    py27_0
sockjs-tornado            1.0.1                    py27_0
sphinx                    1.2.3                    py27_0
spyder                    2.3.4                    py27_1
spyder-app                2.3.4                    py27_0
sqlalchemy                0.9.9                    py27_0
ssl_match_hostname        3.4.0.2                  py27_0
statsmodels               0.6.1                np19py27_0
sympy                     0.7.6                    py27_0
tables                    3.1.1                     <pip>
toolz                     0.7.1                    py27_0
tornado                   4.2                      py27_0
traits                    4.4.0                    py27_0
traitsui                  4.4.0                    py27_0
ujson                     1.33                     py27_0
unicodecsv                0.9.4                    py27_0
werkzeug                  0.10.1                   py27_0
wxpython                  3.0                      py27_0
xlrd                      0.9.3                    py27_0
xlsxwriter                0.6.7                    py27_0
xlwings                   0.3.4                    py27_0
xlwt                      0.7.5                    py27_0
```

**Comment by jat255** [comment] 2015-06-23 18:04
@to266:
 
> You can pass the toolbox to the %hyperspy magic - if it's not (i.e. in all your examples), it just looks for the default one, set in the hyperspy settings.

Thanks for this. I was aware. I wonder if it's possible that it could grab whatever the toolkit specified with `--toolkit` on the command line is...


> We've been considering getting rid of traitsui altogether - it's the last thing keeping hyperspy from migrating to python3. By considering I mean we all talked about that and never actually started doing anything :) Do you think that might reduce the clutter / confusion with the toolboxes?

I certainly think that that would help. Does `traitsui` offer anything other than the GUI components? If not, it seems like these could be 'fairly easily' re-written in `qt`, but I'm not quite sure of what the scope of that undertaking would be :smile:

**Comment by to266** [comment] 2015-06-23 21:49
`traitsui` is there only for the few GUI components (mainly, I think, the span/range selectors + various parameter setting dialogs). I believe it was chosen a long time ago, when the Qt was not yet a "clear winner" among other toolkits. 

Actually moving to python3 is something I'd like quite a bit, so I would be willing to contribute / start the weeding out of the `traitsui`. The problem then is that I never actually had to write any gui code, hence I hesitate being the "main" contributor - I feel more experienced people (@vidartf ?) would have to spend too much time fixing my mistakes... Then again, maybe it's just my imagination. Should be fun to try anyway :)

By the way, Francisco is away until next week - it's highly unlikely you'll get his anaconda packages before then.

**Comment by ericpre** [comment] 2020-09-09 16:55
I don't think this issue still exists. Please re-open if this is not the case.

**Closed by ericpre** 2020-09-09 16:55 UTC
Labels: type: bug
