### ISSUE TITLE
estimate_peak_width(parallel=True) giving rise to nans

### ISSUE THREAD

**Issue by thomasaarholt** [hyperspy/hyperspy#2320] opened 2020-02-20 09:29 UTC
The estimate_peak_width gives a random result of `nan`s when called with `parallel=True` (calling it again yields `nan`s in different places). When called with parallel=False it runs fine. 

[low-loss.zip](https://github.com/hyperspy/hyperspy/files/4229848/low-loss.zip), provided by @JMorzy.

```python
import hyperspy.api as hs
import numpy as np

s = hs.load("low-loss.hspy").inav[0, :]

print("Estimating ZLP width on spectrum image")
print(s.estimate_peak_width(parallel=True).data)

print()
print("Estimating ZLP width on each pixel at a time")
data = []
for i in s.axes_manager:
    data.append(s.inav[i].estimate_peak_width().data[0])
print(np.array(data))
```
![image](https://user-images.githubusercontent.com/2721423/74919748-594e6d80-53cb-11ea-940c-a8e75eb576bd.png)

I've traced the error to [line 1447 in signal1d.py](https://github.com/hyperspy/hyperspy/blob/49fa05c96ca0619615eeccc077f14ed51f1481f1/hyperspy/_signals/signal1d.py#L1447).

**Comment by thomasaarholt** [comment] 2020-02-20 10:11
The smaller I make the window, the fewer nans there are, until there are none appearing on a regular basis. `print(s.estimate_peak_width(window=2000).data)`. With window=None, the entire signal is used, otherwise the signal is of `window` length, centered around the ZLP.


Edit: ugh. The return value of `estimating_function` is:
```python
if len(roots) == 2:
    return np.array(roots)
else:
    return np.full((2,), np.nan)
```
This explains the existance of the nans, but doesn't explain why they only appear with `parallel=True`

**Comment by tjof2** [comment] 2020-02-21 14:58
@thomasaarholt  I don't see this using your example above - is it missing an argument to reproduce it? `hyperspy.__version__` returns `1.5.3.dev` for me, and if I do `s.estimate_peak_width(parallel=True).data` it works fine (no nans)

**Comment by thomasaarholt** [comment] 2020-02-21 16:41
The example should work as-is. You were right to explicitly state `parallel=True`, though. Modifying in case people have changed their preferences. I just reran it now to double check, and in two out of three cases it contains nans. I'm on `'1.6.dev'`.

**Comment by tjof2** [comment] 2020-04-06 10:13
@thomasaarholt  I still don't see this issue on `1.6.dev` - I ran your example 10 times and it worked each time (no nans)

In the definition for `_map_iterate()` I see this, and it all returns sensible things.
```
if parallel is None:
    parallel = preferences.General.parallel
if parallel is True:
    from os import cpu_count
    parallel = cpu_count() or 1
```

**Comment by thomasaarholt** [comment] 2020-04-06 11:13
Can I guess that you are running Linux? I tried again here and same on latest master, lots of nans on the first try:
![image](https://user-images.githubusercontent.com/2721423/78552788-66eb7580-7808-11ea-9162-03a8a3908fab.png)

**Comment by tjof2** [comment] 2020-04-06 11:14
Yes, I'm on Linux.

**Comment by thomasaarholt** [comment] 2020-04-06 11:16
Windows 10 here. Heading out for some sun now, will try and debug this more tonight. I'll compare between Windows 10 (which this is) and Ubuntu on Windows (WSL).

**Comment by thomasaarholt** [comment] 2020-04-08 21:24
This is getting more interesting. I've reduced the problem to one that does not involve any hyperspy code. I use the same UnivariateSpline function from scipy that hyperspy uses, and I randomly get different results for given entries in the mapped arrays. 

Edit: Changed to using a sine function instead of just random values.
```python
# We map scipy's UnivariateSpline on 10 samples of 2000 random data
# Compare the results of using the regular map and the parallel ThreadPoolExecutor map
# On Windows 10, the results do not match.

import numpy as np
import scipy.interpolate

from concurrent.futures import ThreadPoolExecutor
from os import cpu_count
executor = ThreadPoolExecutor(max_workers=cpu_count())
print(f"Processors available: {cpu_count()}")

# parallel=True uses the following map function
parallel_map = executor.map
regular_map = map

samples, length = 10, 2000

x = np.linspace(0, 5*np.pi, length)

data1 = np.repeat(np.sin(x)[None, :], samples, axis=0) # data used for parallel = True
data2 = data1.copy() # data used for parallel = False
data3 = data1.copy() # sanity check checking parallel = False shows same value again

def func(d):
    spline = scipy.interpolate.UnivariateSpline(x, d, s=0)
    return spline.roots()

parallel = list(parallel_map(func, data1))
regular = list(regular_map(func, data2))
sanity = list(regular_map(func, data3))

# Check if numbers are the same - a bit convoluted since the array shape can be different due to the roots function above
for i, (entry1, entry2, entry3) in enumerate(zip(parallel, regular, sanity)):
    if not np.isclose(entry1.sum(), entry2.sum(), rtol=1e-2, atol=1e-2):
        print(f"Index {i}")
        print('Parallel = True', entry1.shape)
        print('Parallel = False 1', entry2.shape)
        print('Parallel = False 2', entry3.shape)        

### Prints some variation of the following, where the number at the end is the shape of the `roots()` result
# Processors available: 8
# Index 5
# Parallel = True (6,)
# Parallel = False 1 (5,)
# Parallel = False 2 (5,)
# Index 7
# Parallel = True (0,)
# Parallel = False 1 (5,)
# Parallel = False 2 (5,)
```

The result is the same with `s=None` as argument to the spline function, I used s=0 since that is what hyperspy is using.

**Comment by tjof2** [comment] 2020-04-09 07:42
Can confirm it works as expected on Linux again.

**Comment by tjof2** [comment] 2020-04-09 07:51
@thomasaarholt does this only happen with UnivariateSpline? I wonder if it might be something to do with calling the underlying FITPACK routines from scipy using ThreadPoolExecutor.

**Comment by thomasaarholt** [comment] 2020-04-09 07:52
I'm trying to find an alternative function that could display the same behaviour. Do you have any suggestions?

**Comment by tjof2** [comment] 2020-04-09 07:57
Do you see any difference between:
```
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor

with ProcessPoolExecutor(max_workers=cpu_count()) as executor:
    parallel = list(executor.map(func, data1))

# with ThreadPoolExecutor(max_workers=cpu_count()) as executor:
#     parallel = list(executor.map(func, data1))

regular = list(map(func, data2))
sanity = list(map(func, data3))
```

**Comment by thomasaarholt** [comment] 2020-04-09 07:58
Btw, in addition to wildly different results like the different shapes shown above, the values can also be only slightly off, see the following figure where I apply UnivariateSpline to the first quarter of a sine curve. Here the last two figures should be identical.
https://gist.github.com/thomasaarholt/851928553f434d08dcb95846006fe1bd
![Figure 1 (2)](https://user-images.githubusercontent.com/2721423/78871869-aa342700-7a48-11ea-8a6d-36315b21b20f.png)

**Comment by tjof2** [comment] 2020-04-09 08:02
Interesting. Let me know if you see a difference between `ThreadPoolExecutor` and `ProcessPoolExecutor`, both in terms of your first problem with shapes as well as your plot.

I think we ought to be using the second instance anyway instead of threads, but I'll await your answer.

**Comment by thomasaarholt** [comment] 2020-04-09 08:14
Does the following work for you in the notebook? It crashes with `BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.` for me.

```python
from concurrent.futures import ProcessPoolExecutor
pool = ProcessPoolExecutor()

def square(n):
    return n*n
numbers = (1, 2, 3, 4)
m = pool.map(square, numbers)
list(m)
```

**Comment by tjof2** [comment] 2020-04-09 08:19
Works fine. To be clear, can you run it OK using `with`? Or still the same issue.

```
from concurrent.futures import ProcessPoolExecutor

def square(n):
    return n*n

numbers = (1, 2, 3, 4)

with ProcessPoolExecutor() as pool:
    m = list(pool.map(square, numbers))
    
m
```

**Comment by thomasaarholt** [comment] 2020-04-09 08:24
The above code works if I run it as a file in a non-interactive python interpreter, i.e.
```python

from concurrent.futures import ProcessPoolExecutor

def square(n):
    return n*n

if __name__ == '__main__':

    numbers = (1, 2, 3, 4)
    with ProcessPoolExecutor(max_workers=4) as executor:
        m = executor.map(square, numbers)
    print(list(m))
```

But ONLY if I put the `square` function outside the \_\_name\_\_ line.

**Comment by thomasaarholt** [comment] 2020-04-09 08:26
> Works fine. To be clear, can you run it OK using `with`? Or still the same issue.
> 
> ```
> from concurrent.futures import ProcessPoolExecutor
> 
> def square(n):
>     return n*n
> 
> numbers = (1, 2, 3, 4)
> 
> with ProcessPoolExecutor() as pool:
>     m = list(pool.map(square, numbers))
>     
> m
> ```

<details><summary>Crashes with the following error:</summary>
<p>

```python
---------------------------------------------------------------------------
BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-6-1842756fe6c7> in <module>
      7 
      8 with ProcessPoolExecutor() as pool:
----> 9     m = list(pool.map(square, numbers))
     10 
     11 m

~\.conda\envs\py5\lib\concurrent\futures\process.py in _chain_from_iterable_of_lists(iterable)
    482     careful not to keep references to yielded objects.
    483     """
--> 484     for element in iterable:
    485         element.reverse()
    486         while element:

~\.conda\envs\py5\lib\concurrent\futures\_base.py in result_iterator()
    609                     # Careful not to keep a reference to the popped future
    610                     if timeout is None:
--> 611                         yield fs.pop().result()
    612                     else:
    613                         yield fs.pop().result(end_time - time.monotonic())

~\.conda\envs\py5\lib\concurrent\futures\_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

~\.conda\envs\py5\lib\concurrent\futures\_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.```

</p>
</details>

**Comment by tjof2** [comment] 2020-04-09 08:26
Oh no wait, this sounds familiar, I think since `ProcessPoolExecutor` uses `multiprocessing` under the hood, this is the issue: https://stackoverflow.com/questions/42602584/how-to-use-multiprocessing-pool-in-an-imported-module

In particular, can you try again based on the example in the second answer? https://stackoverflow.com/a/42617612

**Comment by thomasaarholt** [comment] 2020-04-09 08:30
In order to successfully run ProcessPoolExecutor, I have to run it outside the interactive interpreter. Doing that with the UnivariateSpline example, I get the following:

<details><summary>parallel.py</summary>
<p>

```python

import numpy as np
import matplotlib.pyplot as plt
import scipy.interpolate
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor

from os import cpu_count
def func(d):
    x = np.linspace(0, np.pi/2, len(d))
    spline = scipy.interpolate.UnivariateSpline(x, d)
    return spline(x)

if __name__ == '__main__':
    print(f"Processors available: {cpu_count()}")

    # parallel=True uses the following map function
    regular_map = map

    samples, length = 30, 2000

    x = np.linspace(0, np.pi/2, length)

    data1 = np.repeat(np.sin(x)[None, :], samples, axis=0) # data used for parallel = True

    print('threadpool')
    with ThreadPoolExecutor(max_workers=cpu_count()) as executor:
        parallel = list(executor.map(func, data1))

    print('processpool')
    with ProcessPoolExecutor(max_workers=cpu_count()) as executor:
        parallel2 = list(executor.map(func, data1))
    
    print('normal')
    regular = list(regular_map(func, data1))
    sanity = list(regular_map(func, data1))

    print('finished')

    fig, AX = plt.subplots(nrows=2, ncols=2, figsize=(7, 7))

    ax1, ax2, ax3, ax4 = AX.flatten()
    ax1.set_title('10 identical sin(x)')
    ax2.set_title('10 splines on sin(x) serially')
    ax3.set_title('using ThreadPoolExecutor')
    ax4.set_title('using ProcessPoolExecutor')

    for i in range(samples):
        ax1.plot(x, data1[i])
        ax2.plot(x, regular[i])
        ax3.plot(x, parallel[i])
        ax4.plot(x, parallel2[i])

    plt.tight_layout()
    plt.savefig('spline.png')
```
</p>
</details>

![spline](https://user-images.githubusercontent.com/2721423/78874623-f4b7a280-7a4c-11ea-97c7-da999e16485a.png)

The Spline bug does not appear present with ProcessPoolExecutor, but at least I cannot run it in the interactive interpreter.

**Comment by tjof2** [comment] 2020-04-09 08:31
@thomasaarholt if you try the example I linked to in the SO question, that might help you run it.

**Comment by tjof2** [comment] 2020-04-09 08:31
I think my hunch about ThreadPoolExecutor and the `FITPACK` routines in scipy may be correct...

**Comment by thomasaarholt** [comment] 2020-04-09 08:31
Some more info in [this "works with ubuntu, not with windows" stackoverflow post](https://stackoverflow.com/questions/43836876/processpoolexecutor-works-on-ubuntu-but-fails-with-brokenprocesspool-when-r).

**Comment by tjof2** [comment] 2020-04-09 08:34
@thomasaarholt perhaps you could try replacing the ThreadPoolExecutor with ProcessPoolExecutor in the definition of `_map_iterate()`, and trying your initial HyperSpy example out? https://github.com/hyperspy/hyperspy/blob/RELEASE_next_minor/hyperspy/signal.py#L4077

**EDIT:** ARGH no it won't pickle it :(

**Comment by tjof2** [comment] 2020-04-09 08:38
ARGH no it won't pickle it :(

**Comment by tjof2** [comment] 2020-04-09 08:41
OK using `ProcessPoolExecutor` will likely require more work than I expected to fix `_map_iterate()`. The other option is to tidy up your scipy spline example and report it as a Windows bug over there?

**Comment by thomasaarholt** [comment] 2020-04-09 09:38
I just thought to benchmark the Spline example with some large numbers:

<details><summary>Code</summary>
<p>

```python
import numpy as np
import matplotlib.pyplot as plt
import scipy.interpolate
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor
from time import time
from os import cpu_count
def func(d):
    x = np.linspace(0, np.pi/2, len(d))
    spline = scipy.interpolate.UnivariateSpline(x, d)
    return spline(x)

if __name__ == '__main__':
    print(f"Processors available: {cpu_count()}")

    # parallel=True uses the following map function
    regular_map = map

    samples, length = 10000, 20000

    x = np.linspace(0, np.pi/2, length)

    data1 = np.repeat(np.sin(x)[None, :], samples, axis=0) # data used for parallel = True

    print('threadpool')
    with ThreadPoolExecutor(max_workers=cpu_count()) as executor:
        t = time()
        parallel = list(executor.map(func, data1))
        print(time() - t, 'seconds\n')

    print('processpool')
    with ProcessPoolExecutor(max_workers=cpu_count()) as executor:
        t = time()
        parallel2 = list(executor.map(func, data1))
        print(time() - t, 'seconds\n')
    
    print('normal')
    t = time()
    regular = list(regular_map(func, data1))
    print(time() - t, 'seconds\n')
    sanity = list(regular_map(func, data1))
    print('finished')
```

</p>
</details>

Outputs:
```
Processors available: 8
threadpool
27.34839129447937 seconds

processpool
6.7805304527282715 seconds

normal
28.55653190612793 seconds

finished
```

`map` and `threadpool` have the same performance??

**Comment by thomasaarholt** [comment] 2020-04-09 09:38
I'll report a bug at scipy.

**Comment by tjof2** [comment] 2020-04-09 10:04
@thomasaarholt  yes that's expected from thread pool generally, I think due to the GIL? Any decent blog post on multithreading in Python explains it I think.

Hence why I'd like to move it to processpool

**Comment by thomasaarholt** [comment] 2020-04-09 10:06
How sure are you about it being a problem with FITPACK?
In the parallel.py example above, if I replace UnivariateSpline with `interp1d` (and cubic interpolation like in UnivariateSpline), which also uses FITPACK, I see no issue.

**Comment by tjof2** [comment] 2020-04-09 10:07
I don't mean generally with FITPACK, rather, it might be the specific function called. It may also just be an issue with the Python part too. I can't be sure, just a hunch that's worth highlighting I think

**Comment by ericpre** [comment] 2020-04-09 10:39
According to @to266 (https://github.com/hyperspy/hyperspy/issues/455#issuecomment-370266418), there may be good reasons to consider `ipyparallel`... I don't know how does it compares with the pool available in `concurrent.futures` and I will only mention it here and try to avoid falling in this tempting rabbit hole!

**Comment by thomasaarholt** [comment] 2020-04-09 10:43
scipy/scipy#11828

**Comment by tjof2** [comment] 2020-04-09 10:57
Could we use interp1d to fix your original bug?

**Comment by thomasaarholt** [comment] 2020-04-09 13:26
No, unfortunately not, since it does not have the `roots` method. But one of the other splines might work. Checking now.

**Comment by sturlamolden** [comment] 2020-04-11 20:13
It might be the that the Fortran compilers have different default settings. Fortran subroutines are generally not reentrant, because of things like implicit SAVE attributes. This is also why recursive functions in Fortran must be declared RECURSIVE. Unless we know for certain that the Fortran compiler will produce reentrant binaries, we must protect all calls to Fortran with a lock (preferably not the GIL).

**Comment by sturlamolden** [comment] 2020-04-11 20:23
My guess is that the problem was introduced here:

https://github.com/scipy/scipy/commit/402a1ec63f4c88c1031b3f7bdbfdf75820349340

**Comment by sturlamolden** [comment] 2020-04-11 20:34
If I am correct, this is a general problem with Fortran, not just affecting FITPACK, but also e.g. ODEPACK and FFTPACK. Last time I suggested to protect all Fortran with locks I was ruled down, because we were going to fix it by ensuring the compilers did not use implicit SAVE. However, I do not think anything has actually been done to avoid it.

**Comment by tjof2** [comment] 2020-07-29 21:16
I don't really know if there's a solution here until or if it's ever fixed in SciPy. Should HyperSpy log a warning / raise an error `if parallel is True and os.name == "nt"` since it only affects Windows?

**Closed as completed** 2020-09-08 21:18 UTC
Labels: type: external bug
