### ISSUE TITLE
"line roi" is not working properly

### ISSUE THREAD

**Issue by CorentinLG** [hyperspy/hyperspy#1330] opened 2016-11-16 19:05 UTC
If one does for instance:

line_roi = hs.roi.Line2DROI(2.5,1.5,8.5,1.5,0.3)
sr = line_roi.interactive(sc, color="yellow")

one gets : 
![line roi](https://cloud.githubusercontent.com/assets/23366094/20360954/187129d2-ac36-11e6-97ab-b36bcda4cfb2.png)

The width is not displayed as it should.

Then, the returned signal has a problem, it seems that the x,y coordinate of the line are not properly taken into account.
For instance, when using the line show above, the returned signal is 0 for many points, as if the line was actually running through the void (left of the image). The navigation and signal dimension seem alright though.
![line roi returned signal](https://cloud.githubusercontent.com/assets/23366094/20361419/c4ffea7a-ac37-11e6-82a0-53905594c5b1.png)

**Comment by francisco-dlp** [comment] 2016-11-17 09:56
Thank you for reporting this bug.

**Comment by francisco-dlp** [comment] 2016-11-17 14:28
This looks like a duplicate of #886, @to266, can you confirm this?

**Comment by CorentinLG** [comment] 2016-11-17 14:41
Yes, it does indeed cover the first part of the problem I raised, the line
width which is not displayed properly whe the windows open.

However it does not cover the second part, on the returned signal.

In any case, don't forget I am new to these things, so it could be me who
did not plot things correctly, or did not expect what I should have
expected to be plotted...
It requires someone with experience to check it...

Thanks.
Corentin

2016-11-17 15:28 GMT+01:00 Francisco de la Peña notifications@github.com:

**Comment by francisco-dlp** [comment] 2016-11-17 16:06
It seems to me that the drawing of the ROI is wrong on creation but, as reported in #886, moving it corrects the issue. The data in `sr` seems to be right i.e. in my test it corresponds with what it would be  expected if the ROI was properly drawn. I have slightly modified your example for the test as follows:

``` python
%matplotlib qt4
import hyperspy.api as hs
import numpy as np
im = hs.signals.Signal2D(np.zeros((100, 100)))
im.axes_manager[0].offset = 0.7
im.axes_manager[0].scale = 0.5
im.data[:50, 50:] = 1
im.plot()
line_roi = hs.roi.Line2DROI(10, 20,  30 ,40 ,2)
sr = line_roi.interactive(im, color="yellow")
sr.plot()

```

**Comment by CorentinLG** [comment] 2016-11-19 13:59
Not sure what is happening with my data then.
I tried your example, it returns a plot of the values, but not a image with
energy in X axis and "position along the line in Y with intensity of the
spectrum on the signal axis. Maybe the signal dimension is too small?
On my example (for unknown reason...), it returns both the image and the
signal plots, and some position along the lines give spectra at 0 whereas
there should be signal in them....

I may have done something wrong somewhere (maybe navigaition and signla
dimension are getting confused?), but I can't identify it at this point.
Sorry to bother you with this,
Best

2016-11-17 17:06 GMT+01:00 Francisco de la Peña notifications@github.com:

**Comment by francisco-dlp** [comment] 2016-11-21 09:14
You are right, my example wasn't good. With the following one I can reproduce the bug:

```python

%matplotlib qt4
import hyperspy.api as hs
import numpy as np
im = hs.signals.Signal1D(np.zeros((100, 100, 1024)))
im.axes_manager[0].offset = 0.7
im.axes_manager[0].scale = 0.5
im.data[:50, 50:, 500:600] = 1
im.plot()
line_roi = hs.roi.Line2DROI(10, 20,  30 ,40 ,2)
sr = line_roi.interactive(im, color="yellow")
sr.plot()

```

I think that the issue is that the X and Y coordinates are swapped somewhere in the code. It should be easy to fix. Thanks for spotting and reporting it!

**Comment by thomasaarholt** [comment] 2016-12-14 09:18
Three observations:
`sr.plot()` is not correct even after moving the interactive line profile on im.plot(). I agree with @francisco-dlp's observation of swapped axes.

For each plot, if I move the marker I get this warning:
```python
/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/matplotlib/axes/_base.py:3040: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=0.0, top=0.0
  'bottom=%s, top=%s') % (bottom, top))
```
@francisco-dlp, I think you recognise this error. Penny for your thoughts?

Finally, `sr = line_roi.interactive(im, color="yellow")` has a depreciationwarning:
```python
/Users/thomas/miniconda3/envs/hs/lib/python3.5/site-packages/numpy/lib/shape_base.py:873: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return c.reshape(shape_out)
```

**Comment by thomasaarholt** [comment] 2016-12-14 09:55
I'm pretty sure the error has to do with the signal shape being (X, Y, signal) whilst the data shape is (Y, X, signal).

**Comment by francisco-dlp** [comment] 2017-01-11 11:08
#1330

**Closed as completed by francisco-dlp** 2017-01-11 11:08 UTC
Labels: type: bug
