### ISSUE TITLE
Saving element maps from EDAX .spc files?

### ISSUE THREAD

**Issue by dumblawyer** [hyperspy/hyperspy#1880] opened 2018-03-22 18:18 UTC
Hi,

I am able to product elemental maps after loading an EDAX .spc file, but nothing happens when I select "Save Image" under the "File" menu. I am able to save the histogram map that is automatically generated when the file loads.

Thanks for any advice.

**Comment by jat255** [comment] 2018-03-22 18:31
@dumblawyer can you please explain a little further? Are you trying to save from HyperSpyUI (the user interface), or are you using a Jupyter notebook? Since you are able to produce the maps, this doesn't sound related to the .spc file reader, and may be more of an issue with the graphical backend saving.

**Comment by jat255** [comment] 2018-03-22 18:31
How are you plotting the elemental maps?

**Comment by jat255** [comment] 2018-03-22 18:41
You can also join the [Gitter chat](https://gitter.im/hyperspy/hyperspy) for more interactive help.

**Comment by dumblawyer** [comment] 2018-03-22 21:17
@jat255 I am using the hyperspy UI.  When I open the .spc file, I get a "spectrum image navigator" image and a "spectrum image signal" images. See top image here: https://imgur.com/a/jDGqp

Then I get additional images after I tell Hyperspy to do the element mapping based on the x-ray emissions. See bottom image here: https://imgur.com/a/jDGqp.

When I highlight either the "spectrum image navigator" image or "spectrum image signal" images, and then select File>Save Figure, I get the typical dialog box where I need to specify file name and where it is being saved. When I highlight any of the element maps, I get no such box.

Thanks again.

**Comment by jat255** [comment] 2018-03-22 21:54
@dumblawyer Thanks for the added info. I can confirm the same behavior. I don't believe this is an error in HyperSpy, but instead a problem with HyperSpyUI (the two parts are actually separate). This was reported by @thomasaarholt in hyperspy/hyperspyUI#118. I'm trying to confirm if this problem still exists in the latest version of HyperSpyUI.

**Comment by jat255** [comment] 2018-03-26 19:20
@dumblawyer I can confirm that this is happening even with the latest HyperSpyUI code, so this is definitely a bug, but it's actually in HyperSpyUI, not HyperSpy. 

The relevant issue can be tracked here: https://github.com/hyperspy/hyperspyUI/issues/154

@ericpre @francisco-dlp I think this issue should be closed, since the problem seems to be with the UI instead of HyperSpy directly.

**Comment by jat255** [comment] 2018-03-27 14:32
@dumblawyer, with a better understanding of the problem, I can give you the following as a workaround that you should be able to use until the problem gets fixed and released in a new version:

To get this to work, make sure you have one (and only one) mapped signal open (an .spd file, for instance), and then click the "Map" button in the Element Picker widget to get the line intensity maps. You can then access all of those maps in the console by using the `siglist` variable. Running the following code in the console will replot each of the produced maps, and save it as a .png file. Make sure to change the directory to wherever you want to save it (instead of `"C:/tmp"`):

```python
import matplotlib.pyplot as plt
for s in siglist[1:]:
    s = s.as_signal2D((0,1))
    s.plot()
    new_fn = "C:/tmp/" + plt.gcf().canvas.get_default_filename().replace("\n", "").replace(":", "")
    plt.gcf().savefig(new_fn)
    print("saved to {}".format(new_fn))
    plt.close()
```

**Comment by dumblawyer** [comment] 2018-03-28 00:48
Thanks. I will take a look and confirm whether this works.

**Comment by francisco-dlp** [comment] 2018-03-28 07:28
Closing following @jat255 comment above.

**Closed as completed by francisco-dlp** 2018-03-28 07:28 UTC
