### ISSUE TITLE
Opening of incomplete spectrum images

### ISSUE THREAD

**Issue by Divitini** [hyperspy/hyperspy#2133] opened 2019-03-01 14:14 UTC
Hi,

I recently started encountering problems when loading .emi/.ser EDX datasets. Some datasets do not load; I suspect this is due to the datasets being incomplete scans. Traceback pasted below. As far as I can tell incomplete datasets used to be opened without issues in older versions of Hyperspy.
I am not sure whether this is a bug or one needs a flag in the load() function - can anyone have a look?

I'm using Hyperspy 1.4.1 from the Windows installer bundle (tried both with upgrade from older version and clean re-install).

Example dataset (incomplete SI that doesn't load) here:
https://drive.google.com/drive/folders/1KdRpj0I1o0LGyTqKmPgTfD4BJ9TunUYm?usp=sharing

Thanks,
Giorgio

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-e25301263415> in <module>
----> 1 s1 = hs.load("12.37.58 Drift corrected spectrum image.emi")

~\HyperSpy Bundle\python-3.7.0.amd64\lib\site-packages\hyperspy\io.py in load(filenames, signal_type, stack, stack_axis, new_axis_name, lazy, convert_units, **kwds)
    271             objects = [load_single_file(filename, lazy=lazy,
    272                                         **kwds)
--> 273                        for filename in filenames]
    274 
    275         if len(objects) == 1:

~\HyperSpy Bundle\python-3.7.0.amd64\lib\site-packages\hyperspy\io.py in <listcomp>(.0)
    271             objects = [load_single_file(filename, lazy=lazy,
    272                                         **kwds)
--> 273                        for filename in filenames]
    274 
    275         if len(objects) == 1:

~\HyperSpy Bundle\python-3.7.0.amd64\lib\site-packages\hyperspy\io.py in load_single_file(filename, **kwds)
    308     else:
    309         reader = io_plugins[i]
--> 310         return load_with_reader(filename=filename, reader=reader, **kwds)
    311 
    312 

~\HyperSpy Bundle\python-3.7.0.amd64\lib\site-packages\hyperspy\io.py in load_with_reader(filename, reader, signal_type, convert_units, **kwds)
    315     lazy = kwds.get('lazy', False)
    316     file_data_list = reader.file_reader(filename,
--> 317                                         **kwds)
    318     objects = []
    319 

~\HyperSpy Bundle\python-3.7.0.amd64\lib\site-packages\hyperspy\io_plugins\fei.py in file_reader(filename, *args, **kwds)
    288         return [ser_reader(filename, *args, **kwds), ]
    289     elif ext in emi_extensions:
--> 290         return emi_reader(filename, *args, **kwds)
    291 
    292 

~\HyperSpy Bundle\python-3.7.0.amd64\lib\site-packages\hyperspy\io_plugins\fei.py in emi_reader(filename, dump_xml, **kwds)
    272         _logger.info("Opening %s", f)
    273         try:
--> 274             sers.append(ser_reader(f, objects, **kwds))
    275         except IOError:  # Probably a single spectrum that we don't support
    276             continue

~\HyperSpy Bundle\python-3.7.0.amd64\lib\site-packages\hyperspy\io_plugins\fei.py in ser_reader(filename, objects, *args, **kwds)
    473 
    474     """
--> 475     header, data = load_ser_file(filename)
    476     record_by = guess_record_by(header['DataTypeID'])
    477     ndim = int(header['NumberDimensions'])

~\HyperSpy Bundle\python-3.7.0.amd64\lib\site-packages\hyperspy\io_plugins\fei.py in load_ser_file(filename)
    333                                   dtype=np.dtype(
    334                                       data_dtype_list + tag_dtype_list),
--> 335                                   count=1)
    336             f.seek(offset)
    337         _logger.info("Data info:")

ValueError: setting an array element with a sequence.

**Comment by ericpre** [comment] 2019-03-04 18:17
This is a duplicate of #1928. I have tested @ercius [fixes](https://github.com/ercius/hyperspyPAE/blob/fei_validNumberElements/hyperspy/io_plugins/fei.py) with your file and it works.

@ercius, it seems that your repo (https://github.com/ercius/hyperspyPAE) is not a fork of hyperspy (at least in github terms), because it is not possible to create a PR from your repo to the hyperspy repo. When I get some spare time, I may pull your branch, add a couple of tests and make a PR, so it can get reviewed and merged.

**Comment by ercius** [comment] 2019-03-10 02:28
@ericpre Sorry that this never got finished. I got busy with other things and never got back to this issue. Ive learned a lot more about python and github since I tried to work on this last. Ill check through this code and see if it is up to spec. I can also add some test data I used to validate it.

**Comment by ericpre** [comment] 2019-03-14 16:01
@ercius, it looks to me that you will need to fork hyperspy again to be able to make a PR, I. don't know if there are other way around this.
From a quick look it seems that your branch just need an unit test.

**Comment by Divitini** [comment] 2019-04-01 10:00
Thanks a lot @ercius and @ericpre - seems to be working now (i.e. incomplete spectrum images in emi/ser files are loaded and can be cropped).
To solve the problem, I replaced the fei.py file in 
[windows user folder]\HyperSpy Bundle\python-3.7.0.amd64\Lib\site-packages\hyperspy\io_plugins\
with this:
https://github.com/ercius/hyperspyPAE/blob/fei_validNumberElements/hyperspy/io_plugins/fei.py
.

**Comment by magnunor** [comment] 2019-04-24 15:36
The same bug just surfaced here as well, with a stack of STEM images. See below for those files.

[15.15.50 Scanning Acquire.zip](https://github.com/hyperspy/hyperspy/files/3113027/15.15.50.Scanning.Acquire.zip)

@ercius, your changes indeed fixes the issue! So getting it merged would be very nice :)

**Comment by ericpre** [comment] 2019-06-05 16:04
Fixed in #2160.

**Closed as completed by ericpre** 2019-06-05 16:04 UTC
Labels: type: bug
