### ISSUE TITLE
Hyperspy conflict with scikit-image 0.17.2

### ISSUE THREAD

**Issue by jeinsle** [hyperspy/hyperspy#2402] opened 2020-05-26 14:57 UTC
after setting up yet another work station found that hyperspy1.5.2 does not play nicely with scikit-image 0.17.2.

`import hypyerspy.api as hs`

returns with lots of stuff in between;
`ModuleNotFoundError: No module named 'skimage.feature.register_translation'`

digging through the long list shows that this is tripped by dependency in the signals class looking for the now depreiated `regester_translation` function.

downgrading scikit-image to 0.16.2 fixes issues

**Comment by ericpre** [comment] 2020-05-26 15:09
This is fixed in the development version and on conda-forge. Did you install hyperspy from pypi?

**Comment by jeinsle** [comment] 2020-05-26 16:42
nope used conda forge (actually just cut and pasted command from the hyperspy install page)

**Comment by ericpre** [comment] 2020-05-26 18:23
The python3.8 on windows is missing on anaconda cloud (https://anaconda.org/conda-forge/hyperspy/files), because the build didn't complete:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=160869&view=logs&jobId=3772d104-6254-5db8-f1de-b65daebb998a

Can you confirm that you are using python 3.8?

**Comment by ericpre** [comment] 2020-05-26 19:21
After a couple of restart, it finally worked and the missing package is now uploaded.

**Comment by jeinsle** [comment] 2020-05-26 19:43
I built environment as python 3.7.  Should I have done 3.8?

**Comment by ericpre** [comment] 2020-05-27 15:00
Both python 3.7 and 3.8 should be working fine and indeed I can reproduce the error on windows for python 3.7 only: conda doesn't pick up the last build of hyperspy and it may be a conda bug, not sure.

**Comment by rouviere2** [comment] 2020-06-10 07:17
Installing Anaconda and hyperspy on a virgin PC running windows 10, I got the same mistake (2 trials with python 3.7). In the environment 'hyperspy', where hyperspy was installed, anaconda refused to upgrade to python 3.8 (?). So I created a new virgin environment 'hs' and started to upgrade within Anaconda navigator to python 3.8 : this time it works (?) and by opening a window consol and typing : conda install hyperspy -c conda-forge, the import command : import hypyerspy.api as hs worked without the initial error : GREAT

**Comment by ericpre** [comment] 2020-06-11 13:28
Apparently, when conda solve the dependencies requirement, it doesn't pick up the last build of hyperspy, which has the pinning for scikit-image<0.17... However it is possible to tell conda to install a specific build:
```
conda install hyperspy=1.5.2=*2
```
which will force the dependency resolution to a solution with the expected build.

**Comment by shz224** [comment] 2020-07-08 02:22
I encountered the same problem with you. After remove the old hyperspy and reinstall via `conda install -c conda-forge/label/cf202003 hyperspy`, the problem was solved.

**Comment by farhi** [comment] 2020-07-24 15:58
Hi,
I'd like to inquire when do you plan for the next official release of HypersPy to include a Scikit Image >=17 support ?
Thanks.
PS : I think this is a bug from HypersPy, not Conda/Pip. There is a hard dependency requirement for Sk.Image < 17 which is **not** an external bug.

**Comment by francisco-dlp** [comment] 2020-07-24 17:37
That's right, the current version requires skimage < 0.17. We'll make a release next week with support for skimage 0.17.

**Comment by tjof2** [comment] 2020-08-06 16:08
@ericpre  is this resolved with the latest release?

**Comment by ericpre** [comment] 2020-08-06 16:12
> @ericpre is this resolved with the latest release?

Yes, it is!

**Closed as completed by ericpre** 2020-08-06 16:12 UTC
Labels: type: external bug

**Comment by ericpre** [comment] 2020-08-06 16:28
> Hi,
> I'd like to inquire when do you plan for the next official release of HypersPy to include a Scikit Image >=17 support ?
> Thanks.
> PS : I think this is a bug from HypersPy, not Conda/Pip. There is a hard dependency requirement for Sk.Image < 17 which is **not** an external bug.

@farhi: To clarify the issue here: scikit-image broke their API in a minor release, starting from 0.17 which is not current practise in the python scientific stack. There was no deprecation warning in previous scikit-image release, which means it was not expected and even less predictable.
Unfortunately, HyperSpy was relying on this specific API, which is why it wasn't compatible with scikit-image>0.17.
The possible bug I mentioned earlier for conda is that the conda dependency solver wasn't picking up the latest packages (build hyperspy-1.5.2*_2) of hyperspy, which was made to mitigate the issue. It had a constraint on scikit-image < 0.17 but conda was was installing (hyperspy-1.5.2*_1) which doesn't the scikit-image constraint, even if the [expected behaviour](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html#managing-channels) is to install the package with the highest build number.
